// {{{ 2 "SubmethodForwardDeclaration" ""
private function Abstract(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Abstract" "Begin"
private function Abstract(  ) void {
// }} ""
// {{ 5 "Abstract" "InitLocals"
// }} ""
// {{ 11 1 0 "89646365_e056_4f76_983f60e29bf911cc" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------\nCopyright (C) by HAMILTON Bonaduz AG, CH-7402 Bonaduz.\nAll rights reserved.\nProject : ASW Standard Dialogs\nDescription : This method shows an example for the login dialog\nSoftware Version : 1.1.2\nRevision history:\n- 1.0     2011-10-20 Gian-Marco Schmid library created\n----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "Abstract" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=DWittmer$$valid=0$$time=2012-01-26 07:41$$checksum=70a537e6$$length=087$$