// {{{ 2 "SubmethodForwardDeclaration" ""
private function ArrStr_FindIndex( variable & arrstrStrings[], variable strValue ) variable ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{ 94 1 0 "fe326295_4836_43b6_ad8c4f4e04f3f4d0" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 95 1 0 "79b665e1_a06a_4219_aa613dbcfdc607a6" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 96 1 0 "e3502411_b182_420e_87439ae36bfd9b4b" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
EASYPICKII_STEPS::easyStep_DeInit(ML_STAR);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "ArrStr_FindIndex" "Begin"
private function ArrStr_FindIndex( variable & arrstrStrings[], variable strValue ) variable {
// }} ""
private variable intIndex;
private variable intSize;
// {{ 5 "ArrStr_FindIndex" "InitLocals"
// }} ""
// {{ 86 1 0 "e2140e90_92a8_4cc2_ac5b095e0b8e5bf6" "{72EACF88-8D49-43e3-92C8-2F90E81E3260}"
intSize=arrstrStrings.GetSize();
// }} ""
// {{ 87 1 0 "162aa96e_14dc_431d_b7bf3519a74d5e5d" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(intIndex = 0; intIndex < intSize;)
{
intIndex = intIndex + 1;
// }} ""
// {{ 88 1 0 "7e4a1dd8_18e6_40fd_bad6b05d163d6116" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (arrstrStrings.ElementAt( intIndex -1) == strValue)
{
// }} ""
// {{{ 89 1 0 "428c8f33_18d5_4b28_9778ddba5101b997" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return (intIndex);
// }} ""
// {{ 90 1 0 "7e4a1dd8_18e6_40fd_bad6b05d163d6116" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 91 1 0 "162aa96e_14dc_431d_b7bf3519a74d5e5d" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{{ 92 1 0 "fb65f75c_4fd4_48ec_a0c1456666cd92db" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return (0);
// }} ""
// {{{ 5 "ArrStr_FindIndex" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=technical_support$$valid=0$$time=2016-07-20 13:28$$checksum=fb00b664$$length=096$$