// {{{ 2 "SubmethodForwardDeclaration" ""
private function DisplayErrorAndTerminate( variable iSystemId, variable iErrorCode ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "DisplayErrorAndTerminate" "Begin"
private function DisplayErrorAndTerminate( variable iSystemId, variable iErrorCode ) void {
// }} ""
private variable errMsg;
private dialog dialogHandle29972456E654420184AAAF3D0019546D;
// {{ 5 "DisplayErrorAndTerminate" "InitLocals"
// }} ""
// {{ 85 1 0 "f535141c_e89c_4757_a58bdc429f829bc5" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (iErrorCode != HSLMultiDaisyChainedMediaLine::ERROR_NONE)
{
// }} ""
// {{{ 86 1 0 "ecba1c6c_c88c_4845_ad06b394115bee4a" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
errMsg = HSLMultiDaisyChainedMediaLine::EvaluateErrorMessage(iErrorCode);
// }} ""
// {{ 87 1 0 "386a5182_6461_4ded_adfcf39199a17760" "{21E07B31-8D2E-11d4-A3B8-002035848439}"
dialogHandle29972456E654420184AAAF3D0019546D.SetOutput(Translate("Module #"), iSystemId, Translate(" failed!\nError code = "), iErrorCode, Translate(": "), errMsg);
dialogHandle29972456E654420184AAAF3D0019546D.ShowOutput(Translate("Error raised!"), hslOKOnly | hslInformation | hslDefButton1, hslInfinite);
// }} ""
// {{{ 88 1 0 "0702ac8f_58f7_44a5_a57ac573f9b3f920" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLMultiDaisyChainedMediaLine::TerminateMediaLine(1, 1);
// }} ""
// {{{ 89 1 0 "6c69acc6_07bc_434f_8342d3e835a14eb5" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLMultiDaisyChainedMediaLine::TerminateMediaLine(1, 2);
// }} ""
// {{{ 90 1 0 "bbe86549_8b32_49ad_b1f587a2953f0e9c" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLMultiDaisyChainedMediaLine::TerminateMediaLine(1, 3);
// }} ""
// {{{ 91 1 0 "ab3889d9_d916_40d6_9dc72a183691c3fb" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLMultiDaisyChainedMediaLine::TerminateCommunication(1);
// }} ""
// {{ 92 1 0 "713033ea_fe17_4052_81136db8e7bc79e7" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 93 1 0 "f535141c_e89c_4757_a58bdc429f829bc5" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 94 1 0 "e8443839_3963_46c2_b166f05448ddb652" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return;
// }} ""
// {{{ 5 "DisplayErrorAndTerminate" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2018-06-22 08:41$$checksum=677e3d88$$length=087$$