// {{{ 2 "SubmethodForwardDeclaration" ""
private function _HandleReturnValue( variable i_blnLibrarySuccess, variable i_strLibraryFunctionName ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "_HandleReturnValue" "Begin"
private function _HandleReturnValue( variable i_blnLibrarySuccess, variable i_strLibraryFunctionName ) void {
// }} ""
private variable strDescription;
private variable strLastError;
private variable blnSuccess;
// {{ 5 "_HandleReturnValue" "InitLocals"
// }} ""
// {{ 30 1 0 "438bbb63_eadf_4106_aa254ddd41f4ca42" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (i_blnLibrarySuccess == ASWGLOBAL::BOOL::TRUE)
{
// }} ""
// {{{ 31 1 0 "ef77f41f_05f8_41df_ba43b5943acbbef2" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return;
// }} ""
// {{ 32 1 0 "438bbb63_eadf_4106_aa254ddd41f4ca42" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 33 1 0 "d99d70f2_e20c_4be6_b70c0b9f3441fb2d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLInhecoTECLib::GetLastError(strLastError);
// }} ""
// {{{ 34 1 0 "e6f7838e_e2e3_4467_93087edaaa155e1e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
strDescription = StrConcat4("The following error was reported by the library'", strLastError, "'", "");
// }} ""
// {{{ 35 1 0 "641542d6_4f7d_4948_a54592865401a89c" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TRACELEVEL::TraceAction(TRACE_LEVEL_RELEASE, TRACELEVEL::ACTION::COMPLETE_WITH_ERROR, i_strLibraryFunctionName, _strMethodName, strDescription);
// }} ""
// {{{ 36 1 0 "bbd02dd6_34bb_4ce1_b2a8298a7ccb7db9" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
blnSuccess = HSLInhecoTECLib::Terminate(ASWGLOBAL::BOOL::TRUE);
// }} ""
// {{ 37 1 0 "fc0c4b6d_e43d_4860_89950886ee4fa281" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (blnSuccess == ASWGLOBAL::BOOL::FALSE)
{
// }} ""
// {{{ 38 1 0 "d25c6195_1471_457a_820d4973f37456ea" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLInhecoTECLib::GetLastError(strLastError);
// }} ""
// {{{ 39 1 0 "6c4bcf67_9636_4670_94e139a2d3d570f9" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
strDescription = StrConcat4("The following error was reported by the library'", strLastError, "'", "");
// }} ""
// {{{ 40 1 0 "40d3d517_99cf_41b5_8c087dd7aa69d448" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TRACELEVEL::TraceAction(TRACE_LEVEL_RELEASE, TRACELEVEL::ACTION::COMPLETE_WITH_ERROR, "HSLInhecoTECLib::Terminate", _strMethodName, strDescription);
// }} ""
// {{ 41 1 0 "fc0c4b6d_e43d_4860_89950886ee4fa281" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 42 1 0 "f5aceb07_df6b_45c4_8200013a1453359a" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{{ 5 "_HandleReturnValue" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=labuse1p$$valid=0$$time=2013-09-10 11:33$$checksum=c4cbdd8e$$length=087$$