// {{{ 2 "SubmethodForwardDeclaration" ""
private function _Delay( variable i_intSeconds ) void ;
private function _HandleReturnValue( variable i_blnSuccess, variable i_intDeviceNumber, variable i_strFunctionName, variable i_strMessage ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
private variable strTrace;
private variable blnSuccess;
private variable strMessage;
private variable intLoopCounter;
private variable strFunctionName;
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{ 222 1 0 "ca892f54_2dfa_4557_a21fa34aa6d239ed" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(intLoopCounter = 0; intLoopCounter < _intNumberOfDevices;)
{
intLoopCounter = intLoopCounter + 1;
// }} ""
// {{ 223 1 0 "2bb4fdf5_850b_4dd9_a81f9ed56c0a425c" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (_arrblnInitialized.ElementAt( intLoopCounter -1) == ASWGLOBAL::BOOL::TRUE)
{
// }} ""
// {{{ 224 1 0 "1e752eb0_d4cc_49ce_88aa1d8991a00f06" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
blnSuccess = Inheco_ODTC::Standard::Terminate(_arrintDeviceIDs.ElementAt( intLoopCounter -1), strMessage);
// }} ""
// {{ 225 1 0 "490c5dce_7197_4830_a71653e543469eff" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (blnSuccess == ASWGLOBAL::BOOL::FALSE)
{
// }} ""
// {{{ 226 1 0 "15ceb525_5b3b_4f9f_aa20c81ee6518f5e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
strTrace = StrConcat4("SiLA message was '", strMessage, "'", "");
// }} ""
// {{{ 227 1 0 "8c6a0b8b_684d_42b5_9fe470714e46ca0b" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
strFunctionName = StrConcat2("Terminate device ", intLoopCounter);
// }} ""
// {{{ 228 1 0 "edcc252f_22b7_48eb_bebc11b79c1e100b" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TRACELEVEL::TraceAction(TRACE_LEVEL_RELEASE, TRACELEVEL::ACTION::COMPLETE_WITH_ERROR, strFunctionName, _strMethodName, strTrace);
// }} ""
// {{ 229 1 0 "490c5dce_7197_4830_a71653e543469eff" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 230 1 0 "2bb4fdf5_850b_4dd9_a81f9ed56c0a425c" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 231 1 0 "ca892f54_2dfa_4557_a21fa34aa6d239ed" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "_Delay" "Begin"
private function _Delay( variable i_intSeconds ) void {
// }} ""
private timer hdlDelay;
// {{ 5 "_Delay" "InitLocals"
// }} ""
// {{ 202 1 0 "7764781e_93db_4e94_9cf6a6acf9269b0a" "{B31F353E-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == hdlDelay.SetTimer(i_intSeconds) )
{
    MECC::RaiseRuntimeErrorEx(-1355939584, MECC::IDS::stepNameTimerStart, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{ 203 1 0 "f0b43e5a_9add_4433_8b936c0087273708" "{B31F353F-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == hdlDelay.WaitTimer(hslFalse, hslFalse) )
{
    MECC::RaiseRuntimeErrorEx(-1339162368, MECC::IDS::stepNameTimerWait, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{{ 5 "_Delay" "End"
}
// }} ""
// {{{ 5 "_HandleReturnValue" "Begin"
private function _HandleReturnValue( variable i_blnSuccess, variable i_intDeviceNumber, variable i_strFunctionName, variable i_strMessage ) void {
// }} ""
private variable strTrace;
private variable strMessage;
private variable blnSuccess;
private variable intLoopCounter;
private variable strFunctionName;
// {{ 5 "_HandleReturnValue" "InitLocals"
// }} ""
// {{ 205 1 0 "7349a2d0_a4b2_4657_84e1aec638d73409" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (i_blnSuccess == ASWGLOBAL::BOOL::TRUE)
{
// }} ""
// {{{ 206 1 0 "eb416e69_8738_4b74_ba456404bc067191" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return;
// }} ""
// {{ 207 1 0 "7349a2d0_a4b2_4657_84e1aec638d73409" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 208 1 0 "d67c7783_50c5_4366_a4d74e37a5c24152" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
strTrace = StrConcat4("SiLA message '", i_strMessage, "' received by device ", i_intDeviceNumber);
// }} ""
// {{{ 209 1 0 "074000c3_454e_4357_b7ec2cae806a2720" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TRACELEVEL::TraceAction(TRACE_LEVEL_RELEASE, TRACELEVEL::ACTION::COMPLETE_WITH_ERROR, i_strFunctionName, _strMethodName, strTrace);
// }} ""
// {{ 210 1 0 "3d98adf0_6722_4e2e_99b1b61a9ae3abfc" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(intLoopCounter = 0; intLoopCounter < _intNumberOfDevices;)
{
intLoopCounter = intLoopCounter + 1;
// }} ""
// {{ 211 1 0 "dbfcca6f_feba_471c_8db6e068bfd0e97d" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (_arrblnInitialized.ElementAt( intLoopCounter -1) == ASWGLOBAL::BOOL::TRUE)
{
// }} ""
// {{{ 212 1 0 "2a7e9666_4ced_4a61_ab2292a6d96a56fe" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
blnSuccess = Inheco_ODTC::Standard::Terminate(_arrintDeviceIDs.ElementAt( intLoopCounter -1), strMessage);
// }} ""
// {{ 213 1 0 "fefd0f86_5cbd_4010_b05671a1ccdce052" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (blnSuccess == ASWGLOBAL::BOOL::FALSE)
{
// }} ""
// {{{ 214 1 0 "cdb2fd3d_e2fe_4836_9222aa4fcc7c66a4" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
strTrace = StrConcat4("SiLA message was '", strMessage, "'", "");
// }} ""
// {{{ 215 1 0 "374722fe_ff32_4527_9ce9627edb5c59c9" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
strFunctionName = StrConcat2("Terminate device ", intLoopCounter);
// }} ""
// {{{ 216 1 0 "aa5e9a50_a9e6_4548_9868490af0aa44d2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TRACELEVEL::TraceAction(TRACE_LEVEL_RELEASE, TRACELEVEL::ACTION::COMPLETE_WITH_ERROR, strFunctionName, _strMethodName, strTrace);
// }} ""
// {{ 217 1 0 "fefd0f86_5cbd_4010_b05671a1ccdce052" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 218 1 0 "dbfcca6f_feba_471c_8db6e068bfd0e97d" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 219 1 0 "3d98adf0_6722_4e2e_99b1b61a9ae3abfc" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 220 1 0 "60fb54c1_b7ef_4c07_8c0567d6fd0289db" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{{ 5 "_HandleReturnValue" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=bhuf$$valid=1$$time=2015-11-17 16:26$$checksum=155ca9bc$$length=083$$