// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 20 1 0 "3274d9bb_d8d9_425b_9b6871c3b10b4f2e" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{ 5 1 0 "c9bc5896_28bc_499f_8f7758730b2fdd90" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("***************************************************************************\nCleanUp() submethod\n***************************************************************************"));
// }} ""
// {{ 6 1 0 "f0d64616_5356_4f53_aa9c0e25816cc76f" "ML_STAR:{2931977C-E32F-4471-8B68-F31ED1A866F5}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._2931977C_E32F_4471_8B68_F31ED1A866F5("f0d64616_5356_4f53_aa9c0e25816cc76f"); // LockFrontCover
}
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 8 1 0 "0681c32a_edc8_48cd_ad1de1b591afbf3c" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("***************************************************************************\nStart StartUp() submethod\n***************************************************************************"));
// }} ""
// {{ 9 1 0 "eadba785_8b45_4f34_90079ddd39406843" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("eadba785_8b45_4f34_90079ddd39406843"); // Initialize
}
// }} ""
// {{ 10 1 0 "090e6ff9_a326_49e9_8caddc82815e56f0" "ML_STAR:{EA251BFB-66DE-48D1-83E5-6884B4DD8D11}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._EA251BFB_66DE_48D1_83E5_6884B4DD8D11("090e6ff9_a326_49e9_8caddc82815e56f0"); // MoveAutoLoad
}
// }} ""
// {{ 11 1 0 "6271be34_7471_4fea_8c48193df5f65e08" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 12 1 0 "9498f328_c741_4d22_8d933ee2ddb4dc7f" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (bln_Global_SimulatorMode == 0)
{
// }} ""
// {{ 13 1 0 "477304a5_97cf_4b34_8b2cd13258fbf9cf" "HxFan:{419861B2-AD5B-4F2E-8025-46B0E593A024}"
{
	HxFan.SetComPort("477304a5_97cf_4b34_8b2cd13258fbf9cf"); // SetComPort
}
// }} ""
// {{ 14 1 0 "c34d8334_3807_4d2b_bc609e7a19d6105d" "HxFan:{C3B1A3F9-BD5A-4660-842E-35830B4E80CA}"
{
	HxFan.SetFanSpeed("c34d8334_3807_4d2b_bc609e7a19d6105d"); // SetFanSpeed
}
// }} ""
// {{ 15 1 0 "039b1d9f_6b1c_4f41_a2fd34718a65052e" "HxFan:{166B9764-268C-487A-8D8C-EC3ED594717C}"
{
	HxFan.SetContinuousMode("039b1d9f_6b1c_4f41_a2fd34718a65052e"); // SetContinuousMode
}
// }} ""
// {{ 16 1 0 "9498f328_c741_4d22_8d933ee2ddb4dc7f" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 17 1 0 "6271be34_7471_4fea_8c48193df5f65e08" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 18 1 0 "ece35f81_2773_4857_8c03ba1a40ceec15" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("***************************************************************************\nEnd StartUp() submethod\n***************************************************************************"));
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=djross$$valid=0$$time=2024-06-13 15:16$$checksum=835a5a95$$length=085$$