// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function Startup(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 16 1 0 "ce083b50_d186_4261_a0cebf843521b16e" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 6 1 0 "79e0a4a1_fd8d_4926_a35263f167af338f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR);
// }} ""
// {{{ 7 1 0 "c3693298_c04e_48ad_9ba75dade45163db" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 8 1 0 "a336c3e3_102b_4ab4_818bf51d032d3d1a" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "Startup" "Begin"
private function Startup(  ) void {
// }} ""
// {{ 5 "Startup" "InitLocals"
// }} ""
// {{ 10 1 0 "c02e0e80_f3bc_4558_92e8b61e11a9a4d4" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("c02e0e80_f3bc_4558_92e8b61e11a9a4d4"); // Initialize
}
// }} ""
// {{ 11 1 0 "a18bf1c1_4e00_464a_8e1f1676cb0f9298" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_1000_channels = Translate("Tips_for_channels_1000");
// }} ""
// {{{ 12 1 0 "e4e87237_2a1e_4631_9aa05b9894a03988" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR, 100);
// }} ""
// {{ 13 1 0 "8703c24a_aa3c_431f_985b72eef05e21ce" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_300_channels = Translate("Tips_for_channels_300");
// }} ""
// {{{ 14 1 0 "e0e0a2b9_1858_49dc_819bcbe52edcb7ef" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR, 100);
// }} ""
// {{{ 5 "Startup" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=sforry$$valid=0$$time=2019-03-29 09:14$$checksum=69bae5a5$$length=085$$