// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function Startup(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 38 1 0 "b93b1a12_471d_4252_bf74606a042eb678" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 28 1 0 "966856de_3a7e_42b3_b49c93ef3806a6d1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR);
// }} ""
// {{{ 29 1 0 "182fe3a8_8ced_4f04_9cb0c2550469fa45" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 30 1 0 "87d38900_6a61_40b8_945349ec619283c1" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "Startup" "Begin"
private function Startup(  ) void {
// }} ""
// {{ 5 "Startup" "InitLocals"
// }} ""
// {{ 32 1 0 "e4e169ed_bbda_4da1_8ea8ed8a5d0ce7b9" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("e4e169ed_bbda_4da1_8ea8ed8a5d0ce7b9"); // Initialize
}
// }} ""
// {{ 33 1 0 "0477a604_0339_4b46_9480513ad6a79cac" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_1000_channels = Translate("Tips_for_channels_1000");
// }} ""
// {{{ 34 1 0 "e9feadae_ecd7_409f_b90b13cf619c3e87" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR, 100);
// }} ""
// {{ 35 1 0 "b713426f_638a_42a9_8d218baf9e2030fa" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_300_channels = Translate("Tips_for_channels_300");
// }} ""
// {{{ 36 1 0 "875a4d41_1cf2_4232_a9226d4a045924a3" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR, 100);
// }} ""
// {{{ 5 "Startup" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=sforry$$valid=0$$time=2019-04-04 15:07$$checksum=4e356097$$length=085$$