// {{{ 2 "SubmethodForwardDeclaration" ""
private function Abstract(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 32 1 0 "21bc1c0f_ea52_4dfc_9a721bacd4724158" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
AswStandardDialogs::MessageDialog(Translate(""), 74, 0, 0, 0, 0, Translate(""));
// }} ""
// {{{ 33 1 0 "bdb5b140_3019_44ac_aa5439f4ee357ac4" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
AswStandardDialogs::Terminate();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Abstract" "Begin"
private function Abstract(  ) void {
// }} ""
// {{ 5 "Abstract" "InitLocals"
// }} ""
// {{ 30 1 0 "6de0376b_57d6_48d3_8d3b15ecb19dc5ee" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------\nCopyright (C) by HAMILTON Bonaduz AG, CH-7402 Bonaduz.\nAll rights reserved.\nProject : ASW Standard Dialogs\nDescription : This method shows an example for the checkbox dialog\nSoftware Version : 1.1.2\nRevision history:\n- 1.0     2011-10-20 Gian-Marco Schmid library created\n----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "Abstract" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=ofunke$$valid=0$$time=2013-05-17 07:50$$checksum=642f2696$$length=085$$