// {{{ 2 "SubmethodForwardDeclaration" ""
private function Abstract(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Abstract" "Begin"
private function Abstract(  ) void {
// }} ""
// {{ 5 "Abstract" "InitLocals"
// }} ""
// {{ 8 1 0 "703710e3_0ea4_41be_b33ba329f76cf4f4" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------\nCopyright (C) by HAMILTON Bonaduz AG, CH-7402 Bonaduz.\nAll rights reserved.\nProject : ASW Standard Dialogs\nDescription : This method shows an example for the checkbox dialog\nSoftware Version : 1.1.2\nRevision history:\n- 1.0     2011-10-20 Gian-Marco Schmid library created\n----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "Abstract" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=dwittmer$$valid=0$$time=2013-05-16 08:25$$checksum=e0d3c30e$$length=087$$