// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function GetParams(  ) void ;
private function StartUp(  ) void ;
private function pipette_media( sequence & disp_seq, variable p_vol, variable pre_wet_tips ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 117 1 0 "df7213b0_d6f6_4f60_bba45892edc28a7d" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
private variable array_length;
private variable loopCounter1;
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{ 40 1 0 "f24b71bf_4089_4602_8a9f22f3881fd48f" "{72EACF88-8D49-43e3-92C8-2F90E81E3260}"
array_length=tip_counter_array.GetSize();
// }} ""
// {{ 41 1 0 "14f5f1e7_1604_4446_ba5fffd141028125" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(loopCounter1 = 0; loopCounter1 < array_length;)
{
loopCounter1 = loopCounter1 + 1;
// }} ""
// {{ 42 1 0 "7da00c19_c9a4_424f_8dd53c78ad845499" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 1)
{
// }} ""
// {{{ 43 1 0 "5b7982e2_7df2_43aa_b72d02b80bad5c82" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.Tips_1000_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 44 1 0 "7da00c19_c9a4_424f_8dd53c78ad845499" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 45 1 0 "171e9c13_67c2_4719_9fb6706e49ae1bc5" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 2)
{
// }} ""
// {{{ 46 1 0 "899a529d_af56_4127_9711984a00274bcd" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.Tips_300_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 47 1 0 "171e9c13_67c2_4719_9fb6706e49ae1bc5" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 48 1 0 "c51333d5_848e_4685_bd63d629576dae3b" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 3)
{
// }} ""
// {{{ 49 1 0 "e61732e8_eec2_4565_813f4e2f345fd124" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.Tips_50_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 50 1 0 "c51333d5_848e_4685_bd63d629576dae3b" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 51 1 0 "852b26af_1eee_4ee9_b300ed7e1b92c681" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 4)
{
// }} ""
// {{{ 52 1 0 "69749d56_5b6b_482e_8a465bf2d8d7d887" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.Tips_1000_Offset_pickup, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 53 1 0 "852b26af_1eee_4ee9_b300ed7e1b92c681" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 54 1 0 "14f5f1e7_1604_4446_ba5fffd141028125" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{{ 55 1 0 "a05f49b8_8507_4d34_900b860ec5342143" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR, ML_STAR.clear_96_head_seq);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
private variable array_length;
private variable loopCounter1;
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{{ 86 1 0 "f5e0ce46_089f_4058_9dde19f7ff2f1ec7" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
TIP_HANDLING_WITH_96_HEAD::GetTipCounters(tip_counter_array, 1);
// }} ""
// {{ 87 1 0 "ffb921ef_5505_4788_a474af4da801955f" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 88 1 0 "7c78c178_cb65_40b2_aa3eb1bba9ca9497" "{4900C1F7-0FB7-4033-8253-760BDB9354DC}"
tip_seq_arr.SetSize(0);
// }} ""
// {{ 89 1 0 "a4dd251d_32e5_431c_b92a5f7367fc1052" "{F17B7626-27CB-47f1-8477-8C4158339A6D}"
tip_seq_arr.AddAsLast(ML_STAR.Tips_1000_Channels);
// }} ""
// {{ 90 1 0 "2b5bb22c_67e4_47b7_afb1981e9cd254bf" "{F17B7626-27CB-47f1-8477-8C4158339A6D}"
tip_seq_arr.AddAsLast(ML_STAR.Tips_300_Channels);
// }} ""
// {{ 91 1 0 "064b76a2_f091_4a63_b99195629667b02c" "{F17B7626-27CB-47f1-8477-8C4158339A6D}"
tip_seq_arr.AddAsLast(ML_STAR.Tips_50_Channels);
// }} ""
// {{ 92 1 0 "106ba691_f242_4cc1_b8cb592de9fcf338" "{F17B7626-27CB-47f1-8477-8C4158339A6D}"
tip_seq_arr.AddAsLast(ML_STAR.Tips_1000_Offset_pickup);
// }} ""
// {{ 93 1 0 "ffb921ef_5505_4788_a474af4da801955f" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 94 1 0 "9227a7e0_38a6_49da_b069a827bf345760" "{72EACF88-8D49-43e3-92C8-2F90E81E3260}"
array_length=tip_counter_array.GetSize();
// }} ""
// {{ 95 1 0 "f18f56a2_560b_4e94_ad0b4bf2c846bc9a" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(loopCounter1 = 0; loopCounter1 < array_length;)
{
loopCounter1 = loopCounter1 + 1;
// }} ""
// {{ 96 1 0 "8eb6fbb9_dcbe_40b4_a0799fd8a4724f72" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 1)
{
// }} ""
/* {{ 1 "" "0" */ if(0){  /* }} "" */
// {{{ 97 1 0 "1097ff8f_fbaf_40f4_be4da4345bae311e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.Tips_1000_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR, 100);
// }} ""
/* {{ 1 "" "1" */ } /* }} "" */
// {{{ 98 1 0 "878fe322_8c5b_437a_942d9d5f684df2b1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Read2(ML_STAR.Tips_1000_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 99 1 0 "8eb6fbb9_dcbe_40b4_a0799fd8a4724f72" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 100 1 0 "e513a89e_93b4_4102_a2693cb9c6c77a72" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 2)
{
// }} ""
/* {{ 1 "" "0" */ if(0){  /* }} "" */
// {{{ 101 1 0 "2f48c45e_494e_44bb_a6095f5dd04bbbe4" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.Tips_300_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR, 100);
// }} ""
/* {{ 1 "" "1" */ } /* }} "" */
// {{{ 102 1 0 "313af30f_f6c2_4a56_b1ae8e2300dc51e5" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Read2(ML_STAR.Tips_300_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 103 1 0 "e513a89e_93b4_4102_a2693cb9c6c77a72" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 104 1 0 "0a70d51c_c938_400a_af2e506ebe4b1a39" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 3)
{
// }} ""
/* {{ 1 "" "0" */ if(0){  /* }} "" */
// {{{ 105 1 0 "23e0743e_8d9f_436a_b65e6c0ee2b563d8" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.Tips_50_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR, 100);
// }} ""
/* {{ 1 "" "1" */ } /* }} "" */
// {{{ 106 1 0 "da229816_2a80_4039_8777887bb97c127e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Read2(ML_STAR.Tips_50_Channels, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 107 1 0 "0a70d51c_c938_400a_af2e506ebe4b1a39" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 108 1 0 "9ff271c2_2fd0_4096_ab88645df0184b12" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 4)
{
// }} ""
/* {{ 1 "" "0" */ if(0){  /* }} "" */
// {{{ 109 1 0 "a79de815_8605_4de9_88eeff767cad0918" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.Tips_1000_Offset_pickup, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR, 100);
// }} ""
/* {{ 1 "" "1" */ } /* }} "" */
// {{{ 110 1 0 "b76170d5_3084_449d_ae216329b1a77af8" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Read2(ML_STAR.Tips_1000_Offset_pickup, tip_counter_array.ElementAt( loopCounter1 -1), ML_STAR);
// }} ""
// {{ 111 1 0 "9ff271c2_2fd0_4096_ab88645df0184b12" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 112 1 0 "f18f56a2_560b_4e94_ad0b4bf2c846bc9a" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 113 1 0 "4855942b_ad16_45e7_b53fa4826fddaf30" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("4855942b_ad16_45e7_b53fa4826fddaf30"); // Initialize
}
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
// {{{ 5 "pipette_media" "Begin"
private function pipette_media( sequence & disp_seq, variable p_vol, variable pre_wet_tips ) void {
// }} ""
private sequence tips;
// {{ 5 "pipette_media" "InitLocals"
// }} ""
// {{ 115 1 0 "55670c4f_0d6c_4491_83b13001b086461d" "{B558D25C-EB8A-4a43-8878-125E1847965C}"
{
sequence arrseqAspirate_9AD39E0439984ab9A0A70EC38F0D8CA2[];
sequence arrseqDispense_9AD39E0439984ab9A0A70EC38F0D8CA2[];
arrseqAspirate_9AD39E0439984ab9A0A70EC38F0D8CA2.SetSize(1);
arrseqAspirate_9AD39E0439984ab9A0A70EC38F0D8CA2.SetAt(0, ML_STAR.Media_pipette_from);
arrseqDispense_9AD39E0439984ab9A0A70EC38F0D8CA2.SetSize(1);
arrseqDispense_9AD39E0439984ab9A0A70EC38F0D8CA2.SetAt(0, disp_seq);
PTL::ResetPipettingStateAndSequences("");
PTL::SetPipettingState("UserResponseTime", hslInfinite);
PTL::SetPipettingState("ErrorHandling", 5);
PTL::SetPipettingState("TipCountingEnabled", hslFalse);
PTL::SetPipettingState("TipCountingIdentifier", "");
PTL::SetPipettingState("CopyPatternEnabled", hslFalse);
PTL::SetPipettingState("ExcludeErrorPositionsEnabled", hslFalse);
PTL::SetPipettingState("CalibrateCarrierChannel", -1);
PTL::SetPipettingState("InitializeCustomStepID", 0);
PTL::SetPipettingState("LoadCarrierCustomStepID", 0);
PTL::SetPipettingState("UnloadCarrierCustomStepID", 0);
PTL::SetPipettingState("CalibrateCarrierCustomStepID", 0);
PTL::SetPipettingState("TipPickupCustomStepID", 11);
PTL::SetPipettingState("TipEjectCustomStepID", 0);
PTL::SetPipettingState("AspirateCustomStepID", 0);
PTL::SetPipettingState("DispenseCustomStepID", 0);
PTL::SetPipettingState("PreDispenseCustomStepID", 0);
PTL::SetPipettingState("PostDispenseCustomStepID", 0);
PTL::SetPipettingState("StartNeedleWashCustomStepID", 0);
PTL::SetPipettingState("WaitNeedleWashCustomStepID", 0);
PTL::SetPipettingState("InitializeChannelVariable", "");
PTL::SetPipettingState("InitializeEnabled", hslFalse);
PTL::SetPipettingState("TipPickupChannelVariable", "");
PTL::SetPipettingState("TipPickupEnabled", hslFalse);
PTL::SetPipettingState("TipPickupSequenceReloadable", hslTrue);
PTL::SetPipettingState("TipPickupSequenceReducible", hslTrue);
PTL::SetPipettingState("TipEjectChannelVariable", "");
PTL::SetPipettingState("AspirateMode", 0);
PTL::SetPipettingState("AspirateCLLDSensitivity", 5);
PTL::SetPipettingState("AspirateFluidHeight", 0);
PTL::SetPipettingState("AspirateSubmergeDepth", 2);
PTL::SetPipettingState("AspirateChannelVariable", "");
PTL::SetPipettingState("AspirateMaxHeightDiff", 0);
PTL::SetPipettingState("AspiratePLLDSensitivity", 0);
PTL::SetPipettingState("AspirateLiquidFollowing", hslTrue);
PTL::SetPipettingState("AspirateUserDefinedLiquidClass", "HighVolumeFilter_Water_DispenseJet_Empty");
PTL::SetPipettingState("AspirateSequenceReloadable", hslFalse);
PTL::SetPipettingState("AspirateSequenceReducible", hslFalse);
PTL::SetPipettingState("AspirateSequenceCurrentInitialization", -9);
PTL::SetPipettingState("AspirateSequenceCurrentFinalization", -7);
PTL::SetPipettingState("AspirateSequenceCountInitialization", -10);
PTL::SetPipettingState("AspirateSequenceCountFinalization", -8);
PTL::SetPipettingState("AspirateSequenceCalibration", hslTrue);
PTL::SetPipettingState("DispenseSubmergeDepth", 0);
PTL::SetPipettingState("DispenseChannelVariable", "");
PTL::SetPipettingState("DispenseCLLDSensitivity", 0);
PTL::SetPipettingState("DispenseFluidHeight", 15);
PTL::SetPipettingState("DispenseMode", 1);
PTL::SetPipettingState("DispenseLiquidFollowing", hslFalse);
PTL::SetPipettingState("DispenseUserDefinedLiquidClass", "HighVolumeFilter_Water_DispenseJet_Empty");
PTL::SetPipettingState("DispenseSequenceReloadable", hslFalse);
PTL::SetPipettingState("DispenseSequenceReducible", hslFalse);
PTL::SetPipettingState("DispenseSequenceCurrentInitialization", -10);
PTL::SetPipettingState("DispenseSequenceCurrentFinalization", -7);
PTL::SetPipettingState("DispenseSequenceCountInitialization", -10);
PTL::SetPipettingState("DispenseSequenceCountFinalization", -8);
PTL::SetPipettingState("DispenseSequenceCalibration", hslTrue);
PTL::SetPipettingState("DispenseRestVolumeDestination", 0);
PTL::SetPipettingState("DispenseRestVolumeToAspirateSequenceSurface", hslFalse);
PTL::SetPipettingState("DispenseRestVolumeFluidHeight", 0);
if( 0 == PTL::Pipette3(ML_STAR, tips, arrseqAspirate_9AD39E0439984ab9A0A70EC38F0D8CA2, arrseqDispense_9AD39E0439984ab9A0A70EC38F0D8CA2, 1, 1, p_vol, 0, 2, hslInfinite, hslInfinite, hslInfinite, "", ML_STAR.Media_pipette_from, disp_seq) )
{
    PTL::RaiseRuntimeError(-1573650176, PTL::IDS::smartStepPipette, PTL::IDS::smartStepFailed, "HxGRUCompCmd");
}
}

// }} ""
// {{{ 5 "pipette_media" "End"
}
// }} ""
// {{{ 5 "GetParams" "Begin"
private function GetParams(  ) void {
// }} ""
private variable plate_num_str;
private variable param_dict;
private variable loc;
private variable loopCounter2;
private variable culture_volume_str;
private variable read_line;
private file file1;
private variable split_line[];
// {{ 5 "GetParams" "InitLocals"
// }} ""
// {{ 57 1 0 "7a01da42_8b47_47df_b95fba765c4f4102" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
param_dict = "param_dict";
// }} ""
// {{{ 58 1 0 "e7bc99b6_61ab_4238_8ca4dc94608cc70d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLExtensions::Dictionary::CreateDictionary(param_dict, 2);
// }} ""
// {{ 59 1 0 "80861976_3737_4964_9b3f908bd0b69668" "{B31F3534-5D80-11d4-A5EB-0050DA737D89}"
file1.AddField(1, read_line, hslString);
file1.SetDelimiter(hslAsciiText);
if( 0 == file1.Open("C:\\Program Files (x86)\\HAMILTON\\LMSF_FrontEnd\\parameters.csv", hslRead) )
{
    MECC::RaiseRuntimeErrorEx(-1523711743, MECC::IDS::stepNameFileOpen, MECC::IDS::errorStepFileOpenFailed, "C:\\Program Files (x86)\\HAMILTON\\LMSF_FrontEnd\\parameters.csv", "HxMetEdCompCmd");
}
// }} ""
// {{ 60 1 0 "6345d22b_3f56_4709_8b2f39736401a018" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
loopCounter2 = 0;
while (
   (file1.Eof() == 0)
)
{
loopCounter2 = loopCounter2 + 1;
// }} ""
// {{ 61 1 0 "76038077_b448_440c_9fe104256944f6a5" "{B31F3536-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == file1.ReadRecord() )
{
    MECC::RaiseRuntimeErrorEx(-1490157312, MECC::IDS::stepNameFileRead, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{{ 62 1 0 "f4e634ee_f9da_40a1_8522b53394f8ab98" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
loc = StrFind(read_line, ",");
// }} ""
// {{ 63 1 0 "fc0f8d8c_c60d_477b_abca682ed7c5957a" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loc > 0)
{
// }} ""
// {{{ 64 1 0 "01dcec15_2b8c_445e_88d2de859fe272b9" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
split_line = HSLExtensions::String::Split(read_line, Translate(","), 1);
// }} ""
// {{{ 65 1 0 "496afaa1_ed4d_4eb9_8aca5edf40543976" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLExtensions::Dictionary::AddItem(param_dict, split_line.ElementAt( 1 -1), split_line.ElementAt( 2 -1));
// }} ""
// {{ 66 1 0 "fc0f8d8c_c60d_477b_abca682ed7c5957a" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 67 1 0 "6345d22b_3f56_4709_8b2f39736401a018" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 68 1 0 "414cdfec_a2bd_4f42_9e5c09a5dc5791b0" "{B31F3538-5D80-11d4-A5EB-0050DA737D89}"
if( 0 != file1.Close() )
{
    MECC::RaiseRuntimeErrorEx(-1456602880, MECC::IDS::stepNameFileClose, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
file1.RemoveFields();
// }} ""
// {{ 69 1 0 "11094480_fbe8_4667_b576739d0508a7ee" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 70 1 0 "226e5e7f_c882_4978_a9d8d8cec70c4fc7" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
is_pipetting = HSLExtensions::Dictionary::GetItem(param_dict, Translate("isPipetting"));
// }} ""
// {{ 71 1 0 "d6cbdd15_7572_4550_b72a170137403f63" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 72 1 0 "597b8644_9aa6_48cc_8e3754fc34087531" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
culture_volume_str = HSLExtensions::Dictionary::GetItem(param_dict, Translate("cultureVolume"));
// }} ""
// {{{ 73 1 0 "d6127ca4_e40c_4455_b5d7e2426e091ace" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
culture_volume = StrFVal(culture_volume_str);
// }} ""
// {{ 74 1 0 "f9be0d92_b51f_4c7b_aa59a5e5b92357a4" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (culture_volume > 500)
{
// }} ""
// {{ 75 1 0 "15b30989_5a24_42d9_bf4220ac9fbdf070" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
culture_volume = 500;
// }} ""
// {{ 76 1 0 "f9be0d92_b51f_4c7b_aa59a5e5b92357a4" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
else
{
// }} ""
// {{ 77 1 0 "853fba24_132b_4f74_8f98a691399e32dc" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (culture_volume < 200)
{
// }} ""
// {{ 78 1 0 "3e3fa4fc_445a_47d0_84a43106fd7a93c0" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
culture_volume = 200;
// }} ""
// {{ 79 1 0 "853fba24_132b_4f74_8f98a691399e32dc" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 80 1 0 "f9be0d92_b51f_4c7b_aa59a5e5b92357a4" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 81 1 0 "0724e036_5e81_49b3_a35ff329c8f6bae0" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 82 1 0 "5b2d5816_2230_4a72_8c773da9e97a47bc" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
plate_num_str = HSLExtensions::Dictionary::GetItem(param_dict, Translate("plateNum"));
// }} ""
// {{{ 83 1 0 "41a9b85a_e103_41dd_91065110c735ab1a" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
plate_number = StrIVal(plate_num_str);
// }} ""
// {{ 84 1 0 "39b5414f_f3c9_48ad_8e0e3b1d19f4185f" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 5 "GetParams" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2023-02-09 17:10$$checksum=cfba6224$$length=087$$