// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function GetParams(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 41 1 0 "c83bb2ff_cf39_490d_8722eabdf336d573" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 17 1 0 "19da0ab8_0276_44be_a79d318c06d08523" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 18 1 0 "6274e100_4c67_4f1d_86534db733ff57e8" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 36 1 0 "b1d7b235_f92e_41c0_8a61777250d37c93" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_1000_channels = Translate("Tips_for_channels_1000");
// }} ""
// {{ 37 1 0 "81c5cc9b_d525_4e34_b132a4c546127bed" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_300_channels = Translate("Tips_for_channels_300");
// }} ""
// {{{ 38 1 0 "1b8e1065_86e8_4786_be3b8a62b7ae2f9b" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Read2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{ 39 1 0 "d914109e_fd63_440a_a801b395cc77c76c" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("d914109e_fd63_440a_a801b395cc77c76c"); // Initialize
}
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
// {{{ 5 "GetParams" "Begin"
private function GetParams(  ) void {
// }} ""
private file file1;
private variable param_dict;
private variable loc;
private variable loopCounter2;
private variable read_line;
private variable split_line[];
private variable culture_vol_str;
// {{ 5 "GetParams" "InitLocals"
// }} ""
// {{ 20 1 0 "e04ddf32_6841_4e1a_bcabe6a10e3f7c3d" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 21 1 0 "e5fd69c8_625f_4f8d_b1b5d6837dc53723" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
param_dict = "param_dict";
// }} ""
// {{{ 22 1 0 "d5ef62d7_1f5f_4d97_9749b5c258babe1d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLExtensions::Dictionary::CreateDictionary(param_dict, 2);
// }} ""
// {{ 23 1 0 "c8da815f_6b4b_4f86_9a5df9055bdc4103" "{B31F3534-5D80-11d4-A5EB-0050DA737D89}"
file1.AddField(1, read_line, hslString);
file1.SetDelimiter(hslAsciiText);
if( 0 == file1.Open("C:\\Program Files (x86)\\HAMILTON\\LMSF_FrontEnd\\parameters.csv", hslRead) )
{
    MECC::RaiseRuntimeErrorEx(-1523711743, MECC::IDS::stepNameFileOpen, MECC::IDS::errorStepFileOpenFailed, "C:\\Program Files (x86)\\HAMILTON\\LMSF_FrontEnd\\parameters.csv", "HxMetEdCompCmd");
}
// }} ""
// {{ 24 1 0 "010cfdf3_f241_4a68_b7204ec3e1b6de8b" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
loopCounter2 = 0;
while (
   (file1.Eof() == 0)
)
{
loopCounter2 = loopCounter2 + 1;
// }} ""
// {{ 25 1 0 "c9d846d9_51a5_4c43_b64f721192588ad8" "{B31F3536-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == file1.ReadRecord() )
{
    MECC::RaiseRuntimeErrorEx(-1490157312, MECC::IDS::stepNameFileRead, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{{ 26 1 0 "ce46885b_e33f_4d08_a1093d7d586db51c" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
loc = StrFind(read_line, ",");
// }} ""
// {{ 27 1 0 "363cfd68_0872_47fb_8eff0dcd12858507" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loc > 0)
{
// }} ""
// {{{ 28 1 0 "61a631c0_900a_4866_bb1bec770b54dcf1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
split_line = HSLExtensions::String::Split(read_line, Translate(","), 1);
// }} ""
// {{{ 29 1 0 "3999d0dd_02e7_48bd_8182443ccbc03287" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLExtensions::Dictionary::AddItem(param_dict, split_line.ElementAt( 1 -1), split_line.ElementAt( 2 -1));
// }} ""
// {{ 30 1 0 "363cfd68_0872_47fb_8eff0dcd12858507" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 31 1 0 "010cfdf3_f241_4a68_b7204ec3e1b6de8b" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 32 1 0 "a8930092_4cb2_42e7_8dcb5ecab4890494" "{B31F3538-5D80-11d4-A5EB-0050DA737D89}"
if( 0 != file1.Close() )
{
    MECC::RaiseRuntimeErrorEx(-1456602880, MECC::IDS::stepNameFileClose, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
file1.RemoveFields();
// }} ""
// {{{ 33 1 0 "dbf9a1fb_4435_462d_b12d47c6130a6aea" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
culture_vol_str = HSLExtensions::Dictionary::GetItem(param_dict, Translate("cultureVolume"));
// }} ""
// {{{ 34 1 0 "c3d1bf61_0c3a_4b31_b410b18bc8792620" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
cult_vol = StrFVal(culture_vol_str);
// }} ""
// {{{ 5 "GetParams" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=djross$$valid=0$$time=2019-02-25 18:49$$checksum=dac6ba70$$length=085$$