// {{{ 2 "SubmethodForwardDeclaration" ""
private function Initialize_HHS( variable & var_Local_DeviceID, variable var_Local_Node ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Initialize_HHS" "Begin"
private function Initialize_HHS( variable & var_Local_DeviceID, variable var_Local_Node ) void {
// }} ""
private dialog customDialog0743CBFD7BF4458aAD3E23CBDED03E5D;
private variable bln_Global_SimulatorMode;
private variable loopCounter20;
private variable bln_Local_HHSInitReturn;
private variable int_Global_ReturnDialog;
// {{ 5 "Initialize_HHS" "InitLocals"
var_Local_DeviceID = 0;
// }} ""
// {{ 40 1 0 "4efbc55d_d1f5_4727_8389b8f66b3d1f26" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nInitialize_HHS Start\n=================================================================================================================================="));
// }} ""
Trace ("==================================================================================================================================");
Trace ("Initializing HHS Located at Node:  ", var_Local_Node);
Trace ("==================================================================================================================================");
// {{ 42 1 0 "f296ceca_6a04_4983_b7a734419f5e78b8" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
loopCounter20 = 0;
while (1 == 1)
{
loopCounter20 = loopCounter20 + 1;
// }} ""
// {{{ 43 1 0 "f759a9c4_4bba_4a80_ab49d4b4dafa031d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::SetSimulation(bln_Global_SimulatorMode);
// }} ""
// {{{ 44 1 0 "3fa669e5_4555_4683_b8b2485af0e6d264" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
bln_Local_HHSInitReturn = HSLHamHeaterShaker::CreateUsbDevice(var_Local_Node, var_Local_DeviceID);
// }} ""
// {{ 45 1 0 "a4363ad3_e89f_41c8_aef6a8553d5a953f" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (bln_Local_HHSInitReturn != 0)
{
// }} ""
// {{ 46 1 0 "2e5cf66b_3b2f_4236_95a32fceccc4f51c" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nFailed to Initialize HHS\n=================================================================================================================================="));
// }} ""
// {{{ 47 1 0 "ddb47bbc_b06c_4ca9_ad5d2fff5d43cd1e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::Terminate();
// }} ""
// {{ 48 1 0 "142a86aa_66eb_4710_a43db9c5adb338bc" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialog0743CBFD7BF4458aAD3E23CBDED03E5D.InitCustomDialog( "142a86aa_66eb_4710_a43db9c5adb338bc" );
customDialog0743CBFD7BF4458aAD3E23CBDED03E5D.ShowCustomDialog();
int_Global_ReturnDialog = customDialog0743CBFD7BF4458aAD3E23CBDED03E5D.GetCustomDialogProperty( "ReturnValue" );
// }} ""
// {{ 49 1 0 "f6ee970b_1745_450d_beb150478b976512" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (int_Global_ReturnDialog == 2)
{
// }} ""
// {{ 50 1 0 "a3491aba_384d_4056_b372629532c1c99e" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nMethod Aborted\n=================================================================================================================================="));
// }} ""
// {{ 51 1 0 "8c4caed7_50d9_4f3b_be2576bae6ca44c8" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 52 1 0 "f6ee970b_1745_450d_beb150478b976512" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 53 1 0 "a4363ad3_e89f_41c8_aef6a8553d5a953f" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
else
{
// }} ""
// {{ 54 1 0 "091874ea_2002_4e41_a40d92bc1963c019" "{B31F3533-5D80-11d4-A5EB-0050DA737D89}"
break;
// }} ""
// {{ 55 1 0 "a4363ad3_e89f_41c8_aef6a8553d5a953f" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 56 1 0 "f296ceca_6a04_4983_b7a734419f5e78b8" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 57 1 0 "7bbf69c3_b878_4c61_99ea9ac4325ffd81" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nInitialize_HHS Finish\n=================================================================================================================================="));
// }} ""
// {{{ 5 "Initialize_HHS" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2022-09-21 15:53$$checksum=7fb06ed2$$length=087$$