// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 13 1 0 "3274d9bb_d8d9_425b_9b6871c3b10b4f2e" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{ 10 1 0 "c9bc5896_28bc_499f_8f7758730b2fdd90" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("***************************************************************************\nCleanUp() submethod\n***************************************************************************"));
// }} ""
// {{ 11 1 0 "f0d64616_5356_4f53_aa9c0e25816cc76f" "ML_STAR:{2931977C-E32F-4471-8B68-F31ED1A866F5}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._2931977C_E32F_4471_8B68_F31ED1A866F5("f0d64616_5356_4f53_aa9c0e25816cc76f"); // LockFrontCover
}
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2024-05-01 16:21$$checksum=30f6f201$$length=087$$