// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 20 1 0 "62e3b15a_e915_4e1a_8838a733f1710f4e" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
private variable array_length;
private variable loopCounter1;
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{ 14 1 0 "ee122911_aaeb_4a6e_9d782bf5e9e71684" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 15 1 0 "42c7d655_98f1_45b3_99743f5e038162fc" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
private variable array_length;
private variable loopCounter1;
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 17 1 0 "774b2828_74d9_4e8a_8ec8b986c748c09b" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 18 1 0 "4855942b_ad16_45e7_b53fa4826fddaf30" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("4855942b_ad16_45e7_b53fa4826fddaf30"); // Initialize
}
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=djross$$valid=0$$time=2019-06-01 19:50$$checksum=4eea544f$$length=085$$