// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 18 1 0 "c83bb2ff_cf39_490d_8722eabdf336d573" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 8 1 0 "19da0ab8_0276_44be_a79d318c06d08523" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 9 1 0 "c7d87942_3429_4710_8dc3a881a1202abd" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR);
// }} ""
// {{{ 10 1 0 "6274e100_4c67_4f1d_86534db733ff57e8" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 12 1 0 "4377ea4b_55f4_434c_aa9293e338ad9906" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_1000_channels = Translate("Tips_for_channels_1000");
// }} ""
// {{ 13 1 0 "6d3ad842_21be_433f_84410a0803b5a420" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_300_channels = Translate("Tips_for_channels_300");
// }} ""
// {{{ 14 1 0 "e68fc73d_8fe8_436d_81e430198a42729e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR, 100);
// }} ""
// {{{ 15 1 0 "e3046e5c_fc5c_4dfe_aae4e740d6daedf5" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR, 100);
// }} ""
// {{ 16 1 0 "f6007243_3c1d_40c2_8d1cb257a17da944" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("f6007243_3c1d_40c2_8d1cb257a17da944"); // Initialize
}
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-01-28 13:34$$checksum=748aa5a5$$length=087$$