// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 29 1 0 "eff3f0b1_9c59_4cff_8d7e03a260ec7671" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 22 1 0 "01da151c_2f27_412e_b8573fa710707136" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 23 1 0 "406e9d45_7257_4fa5_8f72888dcd6f2c29" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 25 1 0 "5d749d56_e32c_4966_ba4ad5b1b417e041" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("5d749d56_e32c_4966_ba4ad5b1b417e041"); // Initialize
}
// }} ""
// {{ 26 1 0 "f5694083_8c2b_4608_a6dae71a0ab8e211" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_1000_channels = Translate("Tips_for_channels_1000");
// }} ""
// {{{ 27 1 0 "40a0bf1d_2207_4cb9_936fde84c87407c3" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR, 100);
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-01-28 13:37$$checksum=f551af05$$length=087$$