// {{{ 2 "SubmethodForwardDeclaration" ""
private function A_Definitions(  ) void ;
private function B_Initialise(  ) void ;
private function C_Pipetting(  ) void ;
private function D_Cleanup(  ) void ;
private function _MediaLineReturnHandle( variable i_intReturnCode, variable i_strCommandDescription ) void ;
private function _VersionInfo(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
private dialog customDialogB0E7F1F3BC1B4735B5ABF9BB4E596DC7;
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{ 134 1 0 "6dc7d4d3_cad2_437d_9e9d3b0c0c243137" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Aborting : START\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{ 135 1 0 "7ee15c35_a6e3_4ec5_bf7fae15efdf2036" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 136 1 0 "2c43e72d_cca2_4b2e_919d28feb8b121fd" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialogB0E7F1F3BC1B4735B5ABF9BB4E596DC7.InitCustomDialog( "2c43e72d_cca2_4b2e_919d28feb8b121fd" );
customDialogB0E7F1F3BC1B4735B5ABF9BB4E596DC7.ShowCustomDialog();
// }} ""
// {{{ 137 1 0 "8a426fee_8600_4b56_86df9c2975650fb9" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("------------------------------------ Recovery method filepath - C:\Program Files (x86)\HAMILTON\Methods\[MPE]2\96head crash recovery.med ------------------------------------"), Translate(""));
// }} ""
// {{ 138 1 0 "7ee15c35_a6e3_4ec5_bf7fae15efdf2036" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 139 1 0 "bf93b0f8_c9be_4dca_b694e7f415a6aa27" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 140 1 0 "06af0a39_ab13_49d9_a9a6ec81593401cd" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_blnAbortFlag = 1;
// }} ""
// {{{ 141 1 0 "5a8bbd07_f272_4c3a_957131a0bdddf7f0" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
D_Cleanup();
// }} ""
// {{ 142 1 0 "2bbc1292_005a_4883_81577a3a8c81fa52" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Aborting : END\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "B_Initialise" "Begin"
private function B_Initialise(  ) void {
// }} ""
private variable intMediaLineReturn;
// {{ 5 "B_Initialise" "InitLocals"
// }} ""
// {{ 40 1 0 "868c2448_0b07_4121_80dc59409204bb21" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Initialise : START\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{ 41 1 0 "5d566802_be50_4fc4_a1c8b96396085651" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("5d566802_be50_4fc4_a1c8b96396085651"); // Initialize
}
// }} ""
// {{{ 42 1 0 "8dc02825_88fd_43e1_9c5cd64c4101cb3a" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
_blnSimulationMode = HSLML_STAR::IsSimulatorMode(ML_STAR);
// }} ""
// {{{ 43 1 0 "07ff7d09_461f_44f2_98a66a14df105c5f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_blnSimulationMode = "), _blnSimulationMode);
// }} ""
// {{ 44 1 0 "02ab33fc_9297_415b_a8496052abe10de2" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 45 1 0 "23e12c47_774c_4dee_9116b7be74157e53" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (_blnSimulationMode == 1)
{
// }} ""
// {{ 46 1 0 "a158b8b4_911e_4b18_94b00a1fc50bb480" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_intSimulationMode = 1;
// }} ""
// {{ 47 1 0 "23e12c47_774c_4dee_9116b7be74157e53" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
else
{
// }} ""
// {{ 48 1 0 "308fcc60_4b2c_438d_be4dbcfd636600ba" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_intSimulationMode = 0;
// }} ""
// {{ 49 1 0 "23e12c47_774c_4dee_9116b7be74157e53" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 50 1 0 "514894c2_6b32_47ad_9f96a03ee4a084c4" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 51 1 0 "67557911_0faa_40cd_904dff3226c81586" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
intMediaLineReturn = HSLHamiltonMediaFillModule::Initialize(_intMediaLineCOMPort, _intSimulationMode, _intMediaLineInstrumentID);
// }} ""
// {{{ 52 1 0 "e2917769_7102_49f8_9118648b5e91d90b" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_intMediaLineInstrumentID = "), _intMediaLineInstrumentID);
// }} ""
// {{{ 53 1 0 "dd450f22_f6a6_4398_b3c516b8ad1a05b7" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
intMediaLineReturn = HSLHamiltonMediaFillModule::SetPumpDirection(_intMediaLineInstrumentID, _intMediaLinePumpID, 0);
// }} ""
// {{ 54 1 0 "e9976b33_fa5e_4bb5_a16d8c734550ff80" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 55 1 0 "773ea28b_4075_4492_b01200700fb83229" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
intMediaLineReturn = HSLHamiltonMediaFillModule::FillTrough(_intMediaLineInstrumentID, _intMediaLinePumpID, 75, 1);
// }} ""
// {{{ 56 1 0 "381634ed_074c_453d_a2d2f9b5a00f46c1" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
_MediaLineReturnHandle(intMediaLineReturn, Translate("fill trough"));
// }} ""
// {{ 57 1 0 "514894c2_6b32_47ad_9f96a03ee4a084c4" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 58 1 0 "2cfcd913_804f_4095_a8362ff6a8e9f61e" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Initialise : END\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "B_Initialise" "End"
}
// }} ""
// {{{ 5 "A_Definitions" "Begin"
private function A_Definitions(  ) void {
// }} ""
private variable blnSuccess;
// {{ 5 "A_Definitions" "InitLocals"
// }} ""
// {{ 8 1 0 "87b11dcf_e024_45d3_ba659db5ee11c784" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Definitions : START\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{ 9 1 0 "82b9005a_9af9_47bb_a86eac1bde3d128d" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 10 1 0 "91fbee94_3631_44ba_b462bb9ebb281f6a" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_intMediaLineCOMPort = 8;
// }} ""
// {{{ 11 1 0 "0ba565a7_4159_447f_97ed13e840d77946" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_intMediaLineCOMPort = "), _intMediaLineCOMPort);
// }} ""
// {{ 12 1 0 "e4adcc69_959d_4edf_989862f0784b053f" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_intMediaLinePumpID = 1;
// }} ""
// {{{ 13 1 0 "31f0ed8b_8726_4add_9f325ecf4b995984" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_intMediaLinePumpID = "), _intMediaLinePumpID);
// }} ""
// {{ 14 1 0 "441db9d5_1df6_4c7f_8196ede97cc495a7" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 15 1 0 "2eb01272_e1c2_48c8_9fdc8df48995fe1d" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 16 1 0 "c8c36cda_a452_4cca_9eb85cee11a712e5" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strFilepathStatus = Translate("C:\\HamiltonOutputFiles\\HamiltonStatus.csv");
// }} ""
// {{{ 17 1 0 "1d4491cf_89f8_4d00_ade467a87205cfc3" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_strFilepathStatus = "), _strFilepathStatus);
// }} ""
// {{ 18 1 0 "df9b1f06_70dc_4844_b3d7bb0ad3384e9c" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 19 1 0 "680a69b7_39e4_4a44_b58b155da7aafe68" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
blnSuccess = FileDirectoryLib::CheckIfFileExists(_strFilepathStatus);
// }} ""
// {{ 20 1 0 "eb1f8863_cc68_4b4c_b9672f4be0135d95" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (blnSuccess == 1)
{
// }} ""
// {{{ 21 1 0 "4e465219_0f1c_49b9_825e9296bdfc2c6b" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
FileDirectoryLib::DeleteFile(_strFilepathStatus);
// }} ""
// {{ 22 1 0 "eb1f8863_cc68_4b4c_b9672f4be0135d95" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 23 1 0 "441db9d5_1df6_4c7f_8196ede97cc495a7" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 24 1 0 "7694f810_cf9c_412d_856af4d398c24653" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 25 1 0 "d40b1f2d_e8dc_4e42_a17996d0a724d605" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strTransferPositionGrowthPlate = Translate("PlateHandOff");
// }} ""
// {{{ 26 1 0 "f9764a66_fe96_4479_a465f43c377bc845" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_strTransferPositionGrowthPlate = "), _strTransferPositionGrowthPlate);
// }} ""
// {{ 27 1 0 "96d5a5c5_276f_489f_ba2d8ee330e6d27a" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strTransferPositionTips1000 = Translate("TipsHandOff");
// }} ""
// {{{ 28 1 0 "1e1be3b9_9a76_4c9a_958b804785c9cfc2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_strTransferPositionTips1000 = "), _strTransferPositionTips1000);
// }} ""
// {{ 29 1 0 "c7123862_b124_42c6_b42997d5a170abbb" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 30 1 0 "fe00a23f_cd68_4258_a939f27ed97c58fe" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strWastePositionTips1000 = Translate("Tips1000ulHighVolumeTipWithFilter_Waste");
// }} ""
// {{ 31 1 0 "a14ec125_8b3c_4896_8345fb4d4b33ad15" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strWastePositionTips300 = Translate("Tips300ulStandardVolumeTipWithFilter_Waste");
// }} ""
// {{ 32 1 0 "e5e8822b_cfc2_4384_b07a2610bbdb8f9f" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strWastePositionTips50 = Translate("Tips50ulTipWithFilter_Waste");
// }} ""
// {{ 33 1 0 "764c2020_4424_427d_b04d13bdf1042b63" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 34 1 0 "52beb3ed_66b3_4bf9_ba2a75374a202034" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strGrowthPlateName = Translate("GrowthPlate");
// }} ""
// {{{ 35 1 0 "e0c7c324_dbe6_4447_80af041af6ff4963" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_strGrowthPlateName = "), _strGrowthPlateName);
// }} ""
// {{ 36 1 0 "41875825_b471_4a3e_b55d3db30d32417c" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
_strTips1000Name = Translate("Tips1000");
// }} ""
// {{{ 37 1 0 "e102a99c_3202_4443_b0e1706ef5cc860d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("_strTips1000Name = "), _strTips1000Name);
// }} ""
// {{ 38 1 0 "65957b77_164d_4671_a2b03e7d24f389ae" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Definitions : END\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "A_Definitions" "End"
}
// }} ""
// {{{ 5 "C_Pipetting" "Begin"
private function C_Pipetting(  ) void {
// }} ""
private variable blnSuccess;
private timer tmrSimModeLabwareRequestCompletionFileCreation;
private variable strTransferPosition;
private variable strInputTransferPositionLabwareName;
private variable strInputTransferPositionOccupancy;
private variable blnInputTransferPositionLabwareRequestComplete;
// {{ 5 "C_Pipetting" "InitLocals"
// }} ""
// {{ 60 1 0 "fbccad37_90c1_4a59_855580b2c7a057bd" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Pipetting : START\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{ 61 1 0 "10b0ae0a_e93e_4dee_9e7613eaef264248" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 62 1 0 "19db4f53_a3c8_4f6d_b30f9e2ceb2a67ba" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
MOVE96HEADANDARM::Move96HeadAndArm(ML_STAR);
// }} ""
// {{ 63 1 0 "10b0ae0a_e93e_4dee_9e7613eaef264248" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 64 1 0 "52adee35_11a7_4f47_bfe8a24253faf5be" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 65 1 0 "6af39210_79bf_4dc2_8d411ff476a9c511" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 66 1 0 "e1b5e7cf_7461_4b4d_bbef03ebbbd5f836" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
MOVE96HEADANDARM::Move96HeadAndArm(ML_STAR);
// }} ""
// {{ 67 1 0 "6af39210_79bf_4dc2_8d411ff476a9c511" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 68 1 0 "3d765caf_f8f5_49cf_b4753fb324639ea0" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 69 1 0 "5aef5a76_eeef_4be1_92c7844ba2bf5d4c" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
blnSuccess = LABWAREHANDLING::RequestLabware(_strGrowthPlateName, _strTransferPositionGrowthPlate);
// }} ""
// {{{ 70 1 0 "e895fe40_1016_4a21_91aabf61a07ed900" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("-----Request single plate  : blnSuccess = "), blnSuccess);
// }} ""
// {{ 71 1 0 "3d765caf_f8f5_49cf_b4753fb324639ea0" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 72 1 0 "4962757d_9840_459b_a3df524d40a2c107" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 73 1 0 "fa362455_072d_453e_a3369ef7c2a4b1b5" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
blnSuccess = LABWAREHANDLING::WaitForLabwareRequestCompletion(strTransferPosition, strInputTransferPositionLabwareName, strInputTransferPositionOccupancy);
// }} ""
// {{{ 74 1 0 "6e4b9bc2_b137_4047_87cc43b8ab490315" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("-----Wait For Labware Request Completion : blnSuccess = "), blnSuccess);
// }} ""
// {{ 75 1 0 "4962757d_9840_459b_a3df524d40a2c107" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 76 1 0 "296712c3_8143_458f_8572f8af6a2836da" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 77 1 0 "3ee92706_2593_4016_aac30aa2644ce846" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 78 1 0 "942c91cf_7948_4b70_b1fa8ffed469cd41" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
blnInputTransferPositionLabwareRequestComplete = IF_AND_IF_OR::If_And_3_Variables(strTransferPosition, _strTransferPositionGrowthPlate, strInputTransferPositionLabwareName, _strGrowthPlateName, strInputTransferPositionOccupancy, Translate("1"));
// }} ""
// {{{ 79 1 0 "ecd46044_864a_40ce_98ba3672c23fc113" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("-----blnInputTransferPositionLabwareRequestComplete = "), blnInputTransferPositionLabwareRequestComplete);
// }} ""
// {{ 80 1 0 "35288f18_a1c1_4118_b5ac1c9e8dd23aa3" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 81 1 0 "2cf2f6d5_7c7a_45e9_893f3f812e1377e1" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (blnInputTransferPositionLabwareRequestComplete == 0)
{
// }} ""
// {{{ 82 1 0 "ea48c40d_097e_42a0_a23b6502cda4852e" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
blnSuccess = RUNTIMEERRORHANDLING::TransportError();
// }} ""
// {{{ 83 1 0 "0805999a_8cf5_48f0_8bad5dd1b885282f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("-----RunTime error file creation blnSuccess = "), blnSuccess);
// }} ""
// {{ 84 1 0 "a2e4883a_91e1_4c5e_8d1ce65d3d6e1c17" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 85 1 0 "2cf2f6d5_7c7a_45e9_893f3f812e1377e1" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 86 1 0 "296712c3_8143_458f_8572f8af6a2836da" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 87 1 0 "52adee35_11a7_4f47_bfe8a24253faf5be" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 88 1 0 "1a69ef92_71cd_449a_aaf46a086c7923da" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 89 1 0 "f666a79d_6122_405e_aa19a59dac09d565" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 90 1 0 "928a5d79_92b6_460b_b47c17709617d7fa" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
MOVE96HEADANDARM::Move96HeadAndArm(ML_STAR);
// }} ""
// {{ 91 1 0 "f666a79d_6122_405e_aa19a59dac09d565" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 92 1 0 "8173bdb9_176c_402e_b7306390291d95ac" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 93 1 0 "c0e6a804_d8c2_4ac1_a277e2dbe0098d00" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
blnSuccess = LABWAREHANDLING::ReturnLabware(_strGrowthPlateName, _strTransferPositionGrowthPlate);
// }} ""
// {{{ 94 1 0 "3e12b3a6_c33d_4d09_8429d85ee1b65248" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("-----Request single plate  : blnSuccess = "), blnSuccess);
// }} ""
// {{ 95 1 0 "8173bdb9_176c_402e_b7306390291d95ac" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 96 1 0 "5ee829e3_137a_49f5_bbea533b5d304669" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 97 1 0 "a2cf71e1_8cd6_4f54_8517425fd4187a1d" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
blnSuccess = LABWAREHANDLING::WaitForLabwareReturnCompletion(strTransferPosition, strInputTransferPositionLabwareName, strInputTransferPositionOccupancy);
// }} ""
// {{{ 98 1 0 "6b533098_21b5_40ea_991cf6fee04b2ca8" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("-----Wait For Labware Request Completion : blnSuccess = "), blnSuccess);
// }} ""
// {{ 99 1 0 "5ee829e3_137a_49f5_bbea533b5d304669" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 100 1 0 "1a69ef92_71cd_449a_aaf46a086c7923da" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 101 1 0 "2cd4e3c4_1729_4343_80d3ad1a65272ffe" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Pipetting : END\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "C_Pipetting" "End"
}
// }} ""
// {{{ 5 "D_Cleanup" "Begin"
private function D_Cleanup(  ) void {
// }} ""
private variable intMediaLineReturn;
private file hdlStatusFile;
private variable blnMethodFinishedSuccessfully;
// {{ 5 "D_Cleanup" "InitLocals"
// }} ""
// {{ 103 1 0 "e802d34b_998c_4dea_ab76410fc491929d" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Cleanup : START\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{ 104 1 0 "a9bb5051_29fd_43d5_a4edd0a8053f766d" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (_blnAbortFlag == 0)
{
// }} ""
// {{ 105 1 0 "a1000544_4d54_46bf_a6a828cd28d433ec" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
blnMethodFinishedSuccessfully = 1;
// }} ""
// {{ 106 1 0 "73c35ea5_8f55_47a4_8ad4b583c08d390b" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 107 1 0 "f2c38bbc_75be_4792_bfe4872201161598" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
MOVE96HEADANDARM::Move96HeadAndArm(ML_STAR);
// }} ""
// {{ 108 1 0 "73c35ea5_8f55_47a4_8ad4b583c08d390b" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 109 1 0 "a9bb5051_29fd_43d5_a4edd0a8053f766d" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
else
{
// }} ""
// {{ 110 1 0 "31d8b576_673d_432c_b95b4eca878629ee" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
blnMethodFinishedSuccessfully = 0;
// }} ""
// {{ 111 1 0 "a9bb5051_29fd_43d5_a4edd0a8053f766d" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 112 1 0 "b3f5eb46_1e71_4c1c_a8509fc54fdcb67d" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 113 1 0 "f99ebfec_0e96_4135_829b677fea2a4ff8" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 114 1 0 "86ecb93c_df81_41da_86ae1f300b5896c2" "{B31F3534-5D80-11d4-A5EB-0050DA737D89}"
hdlStatusFile.AddField("Status", blnMethodFinishedSuccessfully, hslInteger);
hdlStatusFile.SetDelimiter(hslCSVDelimited);
if( 0 == hdlStatusFile.Open(_strFilepathStatus, hslWrite) )
{
    MECC::RaiseRuntimeErrorEx(-1523711743, MECC::IDS::stepNameFileOpen, MECC::IDS::errorStepFileOpenFailed, _strFilepathStatus, "HxMetEdCompCmd");
}
// }} ""
// {{ 115 1 0 "b5eba06c_1c96_45a9_83c228b5a77fbdd1" "{B31F3537-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == hdlStatusFile.WriteRecord() )
{
    MECC::RaiseRuntimeErrorEx(-1473380096, MECC::IDS::stepNameFileWrite, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{ 116 1 0 "b9d995d4_f88c_44a5_813d275c2e0fea4c" "{B31F3538-5D80-11d4-A5EB-0050DA737D89}"
if( 0 != hdlStatusFile.Close() )
{
    MECC::RaiseRuntimeErrorEx(-1456602880, MECC::IDS::stepNameFileClose, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
hdlStatusFile.RemoveFields();
// }} ""
// {{ 117 1 0 "b3f5eb46_1e71_4c1c_a8509fc54fdcb67d" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 118 1 0 "dfb5e411_7b16_460c_873f829e14ec20fc" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 119 1 0 "2447c34a_f12c_4815_a61f05f317f7bbf2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
intMediaLineReturn = HSLHamiltonMediaFillModule::Disconnect(_intMediaLineInstrumentID);
// }} ""
// {{{ 120 1 0 "76053770_3dcc_4118_b9737ec4f247e313" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
_MediaLineReturnHandle(intMediaLineReturn, Translate("disconnect"));
// }} ""
// {{ 121 1 0 "dfb5e411_7b16_460c_873f829e14ec20fc" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{ 122 1 0 "47cdd385_4e56_478a_93ec8959e63ba346" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   Cleanup : END\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "D_Cleanup" "End"
}
// }} ""
// {{{ 5 "_VersionInfo" "Begin"
private function _VersionInfo(  ) void {
// }} ""
// {{ 5 "_VersionInfo" "InitLocals"
// }} ""
// {{ 130 1 0 "f3ee5fe8_e530_4f3e_817ec2f4942609ca" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   VersionInfo : START\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{ 131 1 0 "778a9bbd_42a7_4605_a73ed9004f509470" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 132 1 0 "72aadf73_1e46_4f22_92131585b64e25a1" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n\n                                                                   VersionInfo : END\n\n----------------------------------------------------------------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "_VersionInfo" "End"
}
// }} ""
// {{{ 5 "_MediaLineReturnHandle" "Begin"
private function _MediaLineReturnHandle( variable i_intReturnCode, variable i_strCommandDescription ) void {
// }} ""
private dialog customDialog815D9AE778AA4966A9FA54BF3FAC1131;
// {{ 5 "_MediaLineReturnHandle" "InitLocals"
// }} ""
/* {{ 1 "" "0" */ if(0){  /* }} "" */
// {{ 124 1 0 "34f0c25e_6d89_438f_954602370b5c72ec" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (i_intReturnCode == 1)
{
// }} ""
// {{{ 125 1 0 "66597a6a_7e29_4f4b_968732d46bf34bd0" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace4(Translate("--------------------------- Media line error - "), i_strCommandDescription, Translate(" ---------------------------"), Translate(""));
// }} ""
// {{ 126 1 0 "ded83ed0_03dd_49b7_b69ec97a91b0ac8c" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialog815D9AE778AA4966A9FA54BF3FAC1131.InitCustomDialog( "ded83ed0_03dd_49b7_b69ec97a91b0ac8c" );
customDialog815D9AE778AA4966A9FA54BF3FAC1131.SetCustomDialogProperty( "textBlock3.Text", i_strCommandDescription );
customDialog815D9AE778AA4966A9FA54BF3FAC1131.ShowCustomDialog();
// }} ""
// {{ 127 1 0 "9493d34d_1fd2_4f32_b83ecc44d35c1c25" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 128 1 0 "34f0c25e_6d89_438f_954602370b5c72ec" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
/* {{ 1 "" "1" */ } /* }} "" */
// {{{ 5 "_MediaLineReturnHandle" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2018-08-17 11:32$$checksum=d555cd3c$$length=087$$