// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 21 1 0 "6fc49f6b_8aa1_4dc4_a988ffd86d6261aa" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.Tips_1000_Channels, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 22 1 0 "99c3afb8_1971_4253_ae70f61813eb1b00" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.Tips_300_Channels, tip_counter_300_channels, ML_STAR);
// }} ""
// {{{ 23 1 0 "ffdd3113_7f0d_421b_b6c58783cd776df1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.Tips_50_Channels, tip_counter_50_channels, ML_STAR);
// }} ""
// {{{ 24 1 0 "5807d272_7b2a_4f6f_8b79d9d00a7c7fb7" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-03-17 17:08$$checksum=20a95f63$$length=087$$