// {{{ 2 "SubmethodForwardDeclaration" ""
private function _MediaLineReturnHandle( variable i_intReturnCode, variable i_strCommandDescription ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{ 28 1 0 "050c249a_05bb_4d1f_a99abc7d871ed123" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 29 1 0 "5a5f1227_33a1_4dd3_b815a69bf1b892b3" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
intMediaLineReturn = HSLHamiltonMediaFillModule::Disconnect(_intMediaLineInstrumentID);
// }} ""
// {{{ 30 1 0 "8da1a87b_720c_4579_a2a7409119d39d6d" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
_MediaLineReturnHandle(intMediaLineReturn, Translate("disconnect"));
// }} ""
// {{ 31 1 0 "050c249a_05bb_4d1f_a99abc7d871ed123" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "_MediaLineReturnHandle" "Begin"
private function _MediaLineReturnHandle( variable i_intReturnCode, variable i_strCommandDescription ) void {
// }} ""
// {{ 5 "_MediaLineReturnHandle" "InitLocals"
// }} ""
// {{ 23 1 0 "c1807e63_e217_45b3_8a546231420fe0c5" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (i_intReturnCode == 1)
{
// }} ""
// {{{ 24 1 0 "97b23918_a74f_4e08_9a74b7f5efd0e843" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace4(Translate("--------------------------- Media line error - "), i_strCommandDescription, Translate(" ---------------------------"), Translate(""));
// }} ""
// {{ 25 1 0 "a14c504b_ed6d_4929_8cca69303605b4f8" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 26 1 0 "c1807e63_e217_45b3_8a546231420fe0c5" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 5 "_MediaLineReturnHandle" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2018-07-18 13:22$$checksum=d5a46290$$length=087$$