// {{{ 2 "SubmethodForwardDeclaration" ""
private function Initialize_HHS( variable & var_Local_DeviceID, variable var_Local_Node ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Initialize_HHS" "Begin"
private function Initialize_HHS( variable & var_Local_DeviceID, variable var_Local_Node ) void {
// }} ""
private dialog customDialog15301C5CDD2647cd8A7707960DCF871B;
private variable bln_Global_SimulatorMode;
private variable loopCounter20;
private variable bln_Local_HHSInitReturn;
private variable int_Global_ReturnDialog;
// {{ 5 "Initialize_HHS" "InitLocals"
var_Local_DeviceID = 0;
// }} ""
// {{ 14 1 0 "eb435306_084d_4952_b4dab88617310712" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nInitialize_HHS Start\n=================================================================================================================================="));
// }} ""
Trace ("==================================================================================================================================");
Trace ("Initializing HHS Located at Node:  ", var_Local_Node);
Trace ("==================================================================================================================================");
// {{ 16 1 0 "7981e4fa_3340_4524_bb5c4ee8390e6f46" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
loopCounter20 = 0;
while (1 == 1)
{
loopCounter20 = loopCounter20 + 1;
// }} ""
// {{{ 17 1 0 "1a314ca3_4841_4c56_94d266b4ce6143ae" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::SetSimulation(bln_Global_SimulatorMode);
// }} ""
// {{{ 18 1 0 "7789b3a9_0944_4eee_af9b15012ec11838" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
bln_Local_HHSInitReturn = HSLHamHeaterShaker::CreateUsbDevice(var_Local_Node, var_Local_DeviceID);
// }} ""
// {{ 19 1 0 "396f5d81_7a8f_46df_bf8f18f33fe6fd66" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (bln_Local_HHSInitReturn != 0)
{
// }} ""
// {{ 20 1 0 "97846e81_5064_4d5f_8944179c9076789c" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nFailed to Initialize HHS\n=================================================================================================================================="));
// }} ""
// {{{ 21 1 0 "02dca9b2_c632_4bc6_8e3b2efbd088026d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::Terminate();
// }} ""
// {{ 22 1 0 "521c39f3_7ef2_4554_a3fb1fbfc99bfe4c" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialog15301C5CDD2647cd8A7707960DCF871B.InitCustomDialog( "521c39f3_7ef2_4554_a3fb1fbfc99bfe4c" );
customDialog15301C5CDD2647cd8A7707960DCF871B.ShowCustomDialog();
int_Global_ReturnDialog = customDialog15301C5CDD2647cd8A7707960DCF871B.GetCustomDialogProperty( "ReturnValue" );
// }} ""
// {{ 23 1 0 "a1702658_2f57_4d32_b64d0348745501be" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (int_Global_ReturnDialog == 2)
{
// }} ""
// {{ 24 1 0 "dab464d8_22a1_43a1_9fdba6d894b3dd13" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nMethod Aborted\n=================================================================================================================================="));
// }} ""
// {{ 25 1 0 "e08ed263_cd5a_4d98_96cd55fc68b2664d" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 26 1 0 "a1702658_2f57_4d32_b64d0348745501be" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 27 1 0 "396f5d81_7a8f_46df_bf8f18f33fe6fd66" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
else
{
// }} ""
// {{ 28 1 0 "77e66c00_06fd_420d_985860db0cc9df10" "{B31F3533-5D80-11d4-A5EB-0050DA737D89}"
break;
// }} ""
// {{ 29 1 0 "396f5d81_7a8f_46df_bf8f18f33fe6fd66" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 30 1 0 "7981e4fa_3340_4524_bb5c4ee8390e6f46" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 31 1 0 "9d493747_b96e_4ebc_88b71c968f02f92d" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nInitialize_HHS Finish\n=================================================================================================================================="));
// }} ""
// {{{ 5 "Initialize_HHS" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-09-05 11:19$$checksum=39a5ac7c$$length=087$$