// {{{ 2 "SubmethodForwardDeclaration" ""
private function Initialize_HHS( variable & var_Local_DeviceID, variable var_Local_Node ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Initialize_HHS" "Begin"
private function Initialize_HHS( variable & var_Local_DeviceID, variable var_Local_Node ) void {
// }} ""
private dialog customDialog99CFC49249C8494fA8DC9DBE34900009;
private variable bln_Global_SimulatorMode;
private variable loopCounter20;
private variable bln_Local_HHSInitReturn;
private variable int_Global_ReturnDialog;
// {{ 5 "Initialize_HHS" "InitLocals"
var_Local_DeviceID = 0;
// }} ""
// {{ 8 1 0 "cfcdfe03_bfb5_4e91_a6a22ddb8fca11e2" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nInitialize_HHS Start\n=================================================================================================================================="));
// }} ""
Trace ("==================================================================================================================================");
Trace ("Initializing HHS Located at Node:  ", var_Local_Node);
Trace ("==================================================================================================================================");
// {{ 10 1 0 "47a67ece_5d5f_404f_9ae46908b15f5eb5" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
loopCounter20 = 0;
while (1 == 1)
{
loopCounter20 = loopCounter20 + 1;
// }} ""
// {{{ 11 1 0 "25e46cbe_ad85_428e_ae3126e8bf6453a8" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::SetSimulation(bln_Global_SimulatorMode);
// }} ""
// {{{ 12 1 0 "21e76978_36e0_4859_b5aef6673d075ec2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
bln_Local_HHSInitReturn = HSLHamHeaterShaker::CreateUsbDevice(var_Local_Node, var_Local_DeviceID);
// }} ""
// {{ 13 1 0 "990bd0f0_28ad_4ff2_aa24173960aa9df4" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (bln_Local_HHSInitReturn != 0)
{
// }} ""
// {{ 14 1 0 "27c36db3_4fd6_4b87_99fb8b2661675469" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nFailed to Initialize HHS\n=================================================================================================================================="));
// }} ""
// {{{ 15 1 0 "f0715b84_abfc_4733_8f2370ce211c0c9f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::Terminate();
// }} ""
// {{ 16 1 0 "95176c94_7f65_4d72_a60822e9f8e7b491" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialog99CFC49249C8494fA8DC9DBE34900009.InitCustomDialog( "95176c94_7f65_4d72_a60822e9f8e7b491" );
customDialog99CFC49249C8494fA8DC9DBE34900009.ShowCustomDialog();
int_Global_ReturnDialog = customDialog99CFC49249C8494fA8DC9DBE34900009.GetCustomDialogProperty( "ReturnValue" );
// }} ""
// {{ 17 1 0 "053ca697_900f_4eba_93207a6845d1b2c3" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (int_Global_ReturnDialog == 2)
{
// }} ""
// {{ 18 1 0 "323b0773_7fb4_4374_84dcab60240c5a0f" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nMethod Aborted\n=================================================================================================================================="));
// }} ""
// {{ 19 1 0 "39eb8539_b685_49ed_9963272891e69ce3" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 20 1 0 "053ca697_900f_4eba_93207a6845d1b2c3" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 21 1 0 "990bd0f0_28ad_4ff2_aa24173960aa9df4" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
else
{
// }} ""
// {{ 22 1 0 "752354bb_dfff_44ff_95266bb75947c4a8" "{B31F3533-5D80-11d4-A5EB-0050DA737D89}"
break;
// }} ""
// {{ 23 1 0 "990bd0f0_28ad_4ff2_aa24173960aa9df4" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 24 1 0 "47a67ece_5d5f_404f_9ae46908b15f5eb5" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 25 1 0 "db1d088f_dc19_4263_920e4db48c1e2980" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("==================================================================================================================================\nInitialize_HHS Finish\n=================================================================================================================================="));
// }} ""
// {{{ 5 "Initialize_HHS" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-09-05 11:21$$checksum=45fd6f52$$length=087$$