// {{{ 2 "SubmethodForwardDeclaration" ""
private function _ThermoshakeReturnHandle( variable i_blnSuccess, variable i_strCommandDescription ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{ 66 1 0 "d73daeea_576e_43e8_8c39afc86fb2cb41" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 67 1 0 "2e66cbeb_3baa_4d51_b0442f38681ab1e2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
blnThermoshakeSuccess = HSLInhecoTECLib::StopTemperatureControl(_intThermoshakeControlID, _intThermoshakeDeviceID, strThermoshakeErrorCode);
// }} ""
// {{{ 68 1 0 "1c56af2f_dd57_4396_95aefcd93d2aef25" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
_ThermoshakeReturnHandle(blnThermoshakeSuccess, Translate("terminate"));
// }} ""
// {{{ 69 1 0 "bf148cde_00c5_4f0c_85c8207a0e9af531" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
blnThermoshakeSuccess = HSLInhecoTECLib::Terminate(1);
// }} ""
// {{{ 70 1 0 "e5da1974_3b0d_414f_98551474caf92906" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
_ThermoshakeReturnHandle(blnThermoshakeSuccess, Translate("terminate"));
// }} ""
// {{ 71 1 0 "d73daeea_576e_43e8_8c39afc86fb2cb41" "{586C3429-F931-405f-9938-928E22C90BFA}"

// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "_ThermoshakeReturnHandle" "Begin"
private function _ThermoshakeReturnHandle( variable i_blnSuccess, variable i_strCommandDescription ) void {
// }} ""
private dialog customDialogECFEF3BAF0944a51804C9BF2363201CE;
private variable blnSuccess;
private variable strLastError;
// {{ 5 "_ThermoshakeReturnHandle" "InitLocals"
// }} ""
// {{ 53 1 0 "73fed7bb_1b26_4549_a6e16c1e1487b543" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (i_blnSuccess == 0)
{
// }} ""
// {{{ 54 1 0 "eda04da6_7301_4230_9ff5183fe3f4bba0" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLInhecoTECLib::GetLastError(strLastError);
// }} ""
// {{{ 55 1 0 "7364b10e_a1c7_4e39_9210af2153e1477d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace4(Translate("--------------------------- Thermoshake error - "), i_strCommandDescription, Translate(" ---------------------------"), Translate(""));
// }} ""
// {{{ 56 1 0 "0421553a_2e5f_4477_858bac84b0e1c5f8" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace4(Translate("--------------------------- Thermoshake error details - "), strLastError, Translate(" ---------------------------"), Translate(""));
// }} ""
// {{ 57 1 0 "1ac90fb1_dd16_4041_9cfcc4f9cfe8f651" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialogECFEF3BAF0944a51804C9BF2363201CE.InitCustomDialog( "1ac90fb1_dd16_4041_9cfcc4f9cfe8f651" );
customDialogECFEF3BAF0944a51804C9BF2363201CE.SetCustomDialogProperty( "textBlock3.Text", i_strCommandDescription );
customDialogECFEF3BAF0944a51804C9BF2363201CE.SetCustomDialogProperty( "textBlock6.Text", strLastError );
customDialogECFEF3BAF0944a51804C9BF2363201CE.ShowCustomDialog();
// }} ""
// {{{ 58 1 0 "16f50368_1fcc_4f05_bc4a6351b6606290" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
blnSuccess = HSLInhecoTECLib::Terminate(1);
// }} ""
// {{ 59 1 0 "e74796dd_829e_4924_bac3a8ea5c389c82" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (blnSuccess == 0)
{
// }} ""
// {{{ 60 1 0 "b730bc54_383d_4c11_b1572e0ac510081f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLInhecoTECLib::GetLastError(strLastError);
// }} ""
// {{{ 61 1 0 "5b82f969_8432_4895_b9abcc8c6a42aae9" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace4(Translate("--------------------------- Thermoshake error - terminate"), Translate(" ---------------------------"), Translate(""), Translate(""));
// }} ""
// {{ 62 1 0 "e74796dd_829e_4924_bac3a8ea5c389c82" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 63 1 0 "e7ca4b2e_73ec_4249_8d0fa958a1813c5c" "{930D6C31-8EFB-11d4-A3BA-002035848439}"
abort;
// }} ""
// {{ 64 1 0 "73fed7bb_1b26_4549_a6e16c1e1487b543" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 5 "_ThermoshakeReturnHandle" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2018-08-15 14:37$$checksum=44f70232$$length=087$$