// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 154 1 0 "0d3ec356_6a9b_4777_a38d264170a4349e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLMPELib::StopVacuum(1);
// }} ""
// {{{ 155 1 0 "ef68e503_09f3_4e66_b7f1052c5eb9dd85" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLMPELib::Disconnect(1);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=French_C$$valid=0$$time=2018-07-06 03:00$$checksum=2ffab81f$$length=087$$