// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 8 1 0 "09a097d6_e43a_46b2_819b2d46dadc62ef" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR, ML_STAR.clear_96_head_seq);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2025-05-23 11:35$$checksum=df7c0d36$$length=087$$