// {{{ 2 "SubmethodForwardDeclaration" ""
private function HHS_Shake( variable HHSDevice, variable ShakerSpeed, variable ShakeTime ) void ;
private function MagBead_Washing( sequence & WashTipSequence, sequence & SourceReservoir, sequence & TargetPlate, variable WashVolume, variable MixCycles ) void ;
private function Supernatant_Removal( sequence & SourcePlate, sequence & TargetReservoir, variable SupernatantVolume, variable DispenseHeight ) void ;
private function Timer( variable Time ) void ;
private function TransferPlate( sequence & SourcePlate, sequence & DestinationPlate, variable EjectTool ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "HHS_Shake" "Begin"
private function HHS_Shake( variable HHSDevice, variable ShakerSpeed, variable ShakeTime ) void {
// }} ""
// {{ 5 "HHS_Shake" "InitLocals"
// }} ""
// {{{ 109 1 0 "30a1a51a_6428_4baa_a7134e2323ca9fb1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::StartShakerTimed(HHSDevice, ShakerSpeed, ShakeTime);
// }} ""
// {{{ 110 1 0 "b54ecc03_4f0e_491b_a4ea2ca047050ff9" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::WaitForShaker(HHSDevice);
// }} ""
// {{{ 5 "HHS_Shake" "End"
}
// }} ""
// {{{ 5 "Timer" "Begin"
private function Timer( variable Time ) void {
// }} ""
private timer timer1;
// {{ 5 "Timer" "InitLocals"
// }} ""
// {{ 130 1 0 "0810bec1_c6d8_40e8_ae65920dd3fceba8" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
varElapsedTime = 0.0;
// }} ""
// {{ 131 1 0 "b5d16407_6e8b_42a1_9e1358baa819f514" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
ret_StopTimer = 0;
// }} ""
// {{ 132 1 0 "3a4018c6_f4ac_487d_a43c27f390a3bfde" "{B31F353E-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == timer1.SetTimer(Time) )
{
    MECC::RaiseRuntimeErrorEx(-1355939584, MECC::IDS::stepNameTimerStart, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{ 133 1 0 "c28f26d6_9956_45f3_8ef5f717002a53f4" "{B31F353F-5D80-11d4-A5EB-0050DA737D89}"
ret_StopTimer = timer1.WaitTimer(hslTrue, hslTrue);
if (0 == ret_StopTimer)
{
    MECC::RaiseRuntimeErrorEx(-1339162368, MECC::IDS::stepNameTimerWait, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{ 134 1 0 "29abd6a9_b740_4c60_86ae3a427ad7dd69" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (ret_StopTimer == 3)
{
// }} ""
// {{ 135 1 0 "777566b1_ecd4_43e0_a79aa26deb6bb3ed" "{B31F3540-5D80-11d4-A5EB-0050DA737D89}"
varElapsedTime = timer1.GetElapsedTime();
// }} ""
// {{{ 136 1 0 "ebe8d261_c8f2_4d77_a141640ba19f9ee2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("Timer stopped before alotted time.  The elapsed time (in seconds) is: "), varElapsedTime);
// }} ""
// {{ 137 1 0 "81ba14e5_368d_4279_bf00e69a12b26202" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
ret_StopTimer = 0;
// }} ""
// {{ 138 1 0 "29abd6a9_b740_4c60_86ae3a427ad7dd69" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 5 "Timer" "End"
}
// }} ""
// {{{ 5 "TransferPlate" "Begin"
private function TransferPlate( sequence & SourcePlate, sequence & DestinationPlate, variable EjectTool ) void {
// }} ""
// {{ 5 "TransferPlate" "InitLocals"
// }} ""
// {{ 140 1 0 "5ed7f2c9_e573_4ac7_b99c8ac9c7aee5bc" "ML_STAR:{A108628C-BEB7-4CB6-99FD-8523302C700F}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._A108628C_BEB7_4CB6_99FD_8523302C700F("5ed7f2c9_e573_4ac7_b99c8ac9c7aee5bc"); // ZSwapGetPlate
}
// }} ""
// {{ 141 1 0 "92f74e75_f0c3_445e_9b7503c447307065" "ML_STAR:{9DF3DD4B-3B5E-4750-8989-04458D1B134B}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._9DF3DD4B_3B5E_4750_8989_04458D1B134B("92f74e75_f0c3_445e_9b7503c447307065"); // ZSwapPlacePlate
}
// }} ""
// {{{ 5 "TransferPlate" "End"
}
// }} ""
// {{{ 5 "Supernatant_Removal" "Begin"
private function Supernatant_Removal( sequence & SourcePlate, sequence & TargetReservoir, variable SupernatantVolume, variable DispenseHeight ) void {
// }} ""
// {{ 5 "Supernatant_Removal" "InitLocals"
// }} ""
// {{ 116 1 0 "3ca75577_a5e6_43c9_a62b6c82b332d27b" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (SupernatantVolume < 1000)
{
// }} ""
// {{ 117 1 0 "ab487e98_b8b6_47ee_b918d5f7a9eeed57" "ML_STAR:{827392A0-B7E8-4472-9ED3-B45B71B5D27A}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._827392A0_B7E8_4472_9ED3_B45B71B5D27A("ab487e98_b8b6_47ee_b918d5f7a9eeed57"); // Head96Aspirate
}
// }} ""
// {{ 118 1 0 "0bd5557f_65b7_497c_bdc5aba2bf88d628" "ML_STAR:{A48573A5-62ED-4951-9EF9-03207EFE34FB}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._A48573A5_62ED_4951_9EF9_03207EFE34FB("0bd5557f_65b7_497c_bdc5aba2bf88d628"); // Head96Dispense
}
// }} ""
// {{ 119 1 0 "08773360_f8d1_4de6_92a5fa874fadb98f" "ML_STAR:{2880E77A-3D6D-40FE-AF57-1BD1FE13960C}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._2880E77A_3D6D_40FE_AF57_1BD1FE13960C("08773360_f8d1_4de6_92a5fa874fadb98f"); // Head96TipEject
}
// }} ""
// {{ 120 1 0 "3ca75577_a5e6_43c9_a62b6c82b332d27b" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 121 1 0 "dfb3bcd9_da38_4e2a_aa9c6d0922ed53b8" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (SupernatantVolume >= 1000)
{
// }} ""
// {{ 122 1 0 "9644d9df_5db9_4c69_aff286cb624ce7c4" "{B31F3544-5D80-11d4-A5EB-0050DA737D89}"
SupernatantVolume = SupernatantVolume / (2 * 1.0);
// }} ""
// {{ 123 1 0 "f4e9d717_87cc_42a1_8767a5e813c41668" "ML_STAR:{827392A0-B7E8-4472-9ED3-B45B71B5D27A}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._827392A0_B7E8_4472_9ED3_B45B71B5D27A("f4e9d717_87cc_42a1_8767a5e813c41668"); // Head96Aspirate
}
// }} ""
// {{ 124 1 0 "d3db3a58_f63f_444c_81bc0cb973a25177" "ML_STAR:{A48573A5-62ED-4951-9EF9-03207EFE34FB}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._A48573A5_62ED_4951_9EF9_03207EFE34FB("d3db3a58_f63f_444c_81bc0cb973a25177"); // Head96Dispense
}
// }} ""
// {{ 125 1 0 "469bb7f6_d967_46d5_8716e2e5fa43d6ba" "ML_STAR:{827392A0-B7E8-4472-9ED3-B45B71B5D27A}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._827392A0_B7E8_4472_9ED3_B45B71B5D27A("469bb7f6_d967_46d5_8716e2e5fa43d6ba"); // Head96Aspirate
}
// }} ""
// {{ 126 1 0 "33fe7e01_d36e_45fa_b0724a867e152d12" "ML_STAR:{A48573A5-62ED-4951-9EF9-03207EFE34FB}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._A48573A5_62ED_4951_9EF9_03207EFE34FB("33fe7e01_d36e_45fa_b0724a867e152d12"); // Head96Dispense
}
// }} ""
// {{ 127 1 0 "ba4b2857_6d2e_4483_99245cc2b020022c" "ML_STAR:{2880E77A-3D6D-40FE-AF57-1BD1FE13960C}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._2880E77A_3D6D_40FE_AF57_1BD1FE13960C("ba4b2857_6d2e_4483_99245cc2b020022c"); // Head96TipEject
}
// }} ""
// {{ 128 1 0 "dfb3bcd9_da38_4e2a_aa9c6d0922ed53b8" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 5 "Supernatant_Removal" "End"
}
// }} ""
// {{{ 5 "MagBead_Washing" "Begin"
private function MagBead_Washing( sequence & WashTipSequence, sequence & SourceReservoir, sequence & TargetPlate, variable WashVolume, variable MixCycles ) void {
// }} ""
// {{ 5 "MagBead_Washing" "InitLocals"
// }} ""
// {{ 112 1 0 "a5675f26_ad66_4e86_b88f1db4a1030d68" "ML_STAR:{BD0D210B-0816-4C86-A903-D6B2DF73F78B}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._BD0D210B_0816_4C86_A903_D6B2DF73F78B("a5675f26_ad66_4e86_b88f1db4a1030d68"); // Head96TipPickUp
}
// }} ""
// {{ 113 1 0 "4b623f76_0cfb_45ad_a83e8678dac139a6" "ML_STAR:{827392A0-B7E8-4472-9ED3-B45B71B5D27A}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._827392A0_B7E8_4472_9ED3_B45B71B5D27A("4b623f76_0cfb_45ad_a83e8678dac139a6"); // Head96Aspirate
}
// }} ""
// {{ 114 1 0 "f3750997_6a3f_4ce3_8a3fce4601b67614" "ML_STAR:{A48573A5-62ED-4951-9EF9-03207EFE34FB}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._A48573A5_62ED_4951_9EF9_03207EFE34FB("f3750997_6a3f_4ce3_8a3fce4601b67614"); // Head96Dispense
}
// }} ""
// {{{ 5 "MagBead_Washing" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=djross$$valid=0$$time=2019-04-19 11:28$$checksum=232a4b1a$$length=085$$