// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 28 1 0 "2daf0f56_b989_41eb_a4714263199d3866" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
NIST_DEVICE_CONTROLLERS::TerminateODTC(Device);
// }} ""
// {{{ 29 1 0 "42ed4ed9_2c2c_4006_8de5eee4d2a37459" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
NIST_DEVICE_CONTROLLERS::TerminateCPAC();
// }} ""
// {{{ 30 1 0 "b950c0c7_8c5d_4d36_83f7d26a99609ae6" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::Terminate();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-07-09 13:14$$checksum=6852f0ff$$length=087$$