// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function GetParams(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 34 1 0 "b7901731_8011_459c_bc422332a7719aff" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 14 1 0 "c334c71d_7da1_47a0_9c62dc9af140924e" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR, ML_STAR.clear_96_head_seq);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 32 1 0 "4855942b_ad16_45e7_b53fa4826fddaf30" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("4855942b_ad16_45e7_b53fa4826fddaf30"); // Initialize
}
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
// {{{ 5 "GetParams" "Begin"
private function GetParams(  ) void {
// }} ""
private variable param_dict;
private variable loc;
private variable read_line;
private file file1;
private variable split_line[];
private variable loopCounter2;
private variable key_exists;
private variable preheat_str;
// {{ 5 "GetParams" "InitLocals"
// }} ""
// {{ 16 1 0 "71f4731a_2329_41e3_b8d4fb2f24bdf973" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
param_dict = "param_dict";
// }} ""
// {{{ 17 1 0 "99b047b2_cff8_4206_a80c5a49a2aeb658" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLExtensions::Dictionary::CreateDictionary(param_dict, 2);
// }} ""
// {{ 18 1 0 "795b3299_cf6a_4691_9841b6684097743b" "{B31F3534-5D80-11d4-A5EB-0050DA737D89}"
file1.AddField(1, read_line, hslString);
file1.SetDelimiter(hslAsciiText);
if( 0 == file1.Open("C:\\Program Files (x86)\\HAMILTON\\LMSF_FrontEnd\\parameters.csv", hslRead) )
{
    MECC::RaiseRuntimeErrorEx(-1523711743, MECC::IDS::stepNameFileOpen, MECC::IDS::errorStepFileOpenFailed, "C:\\Program Files (x86)\\HAMILTON\\LMSF_FrontEnd\\parameters.csv", "HxMetEdCompCmd");
}
// }} ""
// {{ 19 1 0 "daaf2fc6_6031_418e_98822820cb33c9bc" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
loopCounter2 = 0;
while (
   (file1.Eof() == 0)
)
{
loopCounter2 = loopCounter2 + 1;
// }} ""
// {{ 20 1 0 "e3a9a63c_764f_4dc2_892d5c836ff8d8c0" "{B31F3536-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == file1.ReadRecord() )
{
    MECC::RaiseRuntimeErrorEx(-1490157312, MECC::IDS::stepNameFileRead, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{{ 21 1 0 "90155ffc_0c22_4e8d_8d3a70f5570edef3" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
loc = StrFind(read_line, ",");
// }} ""
// {{ 22 1 0 "f22d2faf_8482_42e2_b8cec2dc7d9932e6" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loc > 0)
{
// }} ""
// {{{ 23 1 0 "3d5cfe75_39be_454d_85fde4aa46688e98" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
split_line = HSLExtensions::String::Split(read_line, Translate(","), 1);
// }} ""
// {{{ 24 1 0 "68561151_ee14_45ef_a36fa7fc85e514a7" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLExtensions::Dictionary::AddItem(param_dict, split_line.ElementAt( 1 -1), split_line.ElementAt( 2 -1));
// }} ""
// {{ 25 1 0 "f22d2faf_8482_42e2_b8cec2dc7d9932e6" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 26 1 0 "daaf2fc6_6031_418e_98822820cb33c9bc" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 27 1 0 "8c8c2f2a_5545_468c_a9d57cebe7efb268" "{B31F3538-5D80-11d4-A5EB-0050DA737D89}"
if( 0 != file1.Close() )
{
    MECC::RaiseRuntimeErrorEx(-1456602880, MECC::IDS::stepNameFileClose, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
file1.RemoveFields();
// }} ""
// {{ 28 1 0 "88499e7a_6a40_4446_8ba56d9d5ef3d172" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 29 1 0 "e3c1d059_4d1e_4db7_b252d89fe996a931" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
preheat_str = HSLExtensions::Dictionary::GetItem(param_dict, Translate("preheatTime"));
// }} ""
// {{{ 30 1 0 "ea7064f0_b91c_43bf_896016544703257e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
preheat_time = StrIVal(preheat_str);
// }} ""
// {{{ 5 "GetParams" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=djross$$valid=0$$time=2024-12-22 13:52$$checksum=b34164d6$$length=085$$