// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 22 1 0 "6ea14039_c63a_4a51_af782ebeb6497b5d" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
CleanUp();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{ 19 1 0 "019cb820_8939_4ffb_92903d977989104e" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("019cb820_8939_4ffb_92903d977989104e"); // Initialize
}
// }} ""
// {{{ 20 1 0 "b461e77e_301d_48cb_8424760e126c61f9" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR, ML_STAR.clear_96_head_seq);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=djross$$valid=0$$time=2022-11-07 09:28$$checksum=7492b2c3$$length=085$$