// {{{ 2 "SubmethodForwardDeclaration" ""
private function Abstract(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 14 1 0 "afed6e8b_13c2_4e7c_bd47b538324e37e2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
AswStandardDialogs::MessageDialog(Translate("Error"), AswStandardDialogs::IconType::Error, AswStandardDialogs::ButtonType::Ok, 0, 0, 5, Translate("Error raised"));
// }} ""
// {{{ 15 1 0 "8da75be6_9cdf_483e_96ce8bdf36f115f2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
AswStandardDialogs::Terminate();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Abstract" "Begin"
private function Abstract(  ) void {
// }} ""
// {{ 5 "Abstract" "InitLocals"
// }} ""
// {{ 12 1 0 "78956bca_aa07_4997_8d70687abab85638" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------\nCopyright (C) by HAMILTON Bonaduz AG, CH-7402 Bonaduz.\nAll rights reserved.\nProject : ASW Standard Dialogs\nDescription : This method shows an example for the checkbox dialog\nSoftware Version : 1.1.2\nRevision history:\n- 1.0     2011-10-20 Gian-Marco Schmid library created\n----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "Abstract" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=ofunke$$valid=0$$time=2011-12-13 10:31$$checksum=13b8bcdf$$length=085$$