// {{{ 2 "SubmethodForwardDeclaration" ""
private function Abstract(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "Abstract" "Begin"
private function Abstract(  ) void {
// }} ""
// {{ 5 "Abstract" "InitLocals"
// }} ""
// {{ 7 1 0 "16cf3936_125c_41e5_8683491590795d0b" "{F07B0071-8EFC-11d4-A3BA-002035848439}"
MECC::TraceComment(Translate("----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------\nCopyright (C) by HAMILTON Bonaduz AG, CH-7402 Bonaduz.\nAll rights reserved.\nProject : ASW Standard Dialogs\nDescription : This method shows an example for the checkbox dialog\nSoftware Version : 1.1.2\nRevision history:\n- 1.0     2011-10-20 Gian-Marco Schmid library created\n----------------------------------------------------------------------------------------------------------------------\n----------------------------------------------------------------------------------------------------------------------"));
// }} ""
// {{{ 5 "Abstract" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=ofunke$$valid=0$$time=2011-12-13 10:31$$checksum=3d7eadcf$$length=085$$