// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
private dialog customDialog5A1245BAB6A74a5dB933197DCF927B5D;
private variable User_choice;
private dialog customDialog1BA6452FBD7847e483AFB43608368C20;
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 43 1 0 "6b92fbe3_f1d6_4a73_ade8c090d20df13d" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_1000_channels = Translate("Tips_for_channels_1000");
// }} ""
// {{ 44 1 0 "61b36e3a_ba3c_4212_b19d15dbd4a52ed8" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_300_channels = Translate("Tips_for_channels_300");
// }} ""
// {{ 45 1 0 "c26a6b7c_170b_49f0_b36871b5d5699cdb" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialog5A1245BAB6A74a5dB933197DCF927B5D.InitCustomDialog( "c26a6b7c_170b_49f0_b36871b5d5699cdb" );
customDialog5A1245BAB6A74a5dB933197DCF927B5D.ShowCustomDialog();
User_choice = customDialog5A1245BAB6A74a5dB933197DCF927B5D.GetCustomDialogProperty( "ReturnValue" );
// }} ""
// {{{ 46 1 0 "ad2c5098_8199_4489_a4c74889ef8d4b0d" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR, 100);
// }} ""
// {{ 47 1 0 "a8649353_0d77_496b_b07edd38f03e8228" "{998A7CCC-4374-484D-A6ED-E8A4F0EB71BA}"
customDialog1BA6452FBD7847e483AFB43608368C20.InitCustomDialog( "a8649353_0d77_496b_b07edd38f03e8228" );
customDialog1BA6452FBD7847e483AFB43608368C20.ShowCustomDialog();
User_choice = customDialog1BA6452FBD7847e483AFB43608368C20.GetCustomDialogProperty( "ReturnValue" );
// }} ""
// {{{ 48 1 0 "79cbe22b_d734_4a42_ba9e25171a51550b" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Edit2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR, 100);
// }} ""
// {{ 49 1 0 "160de43a_c4c2_4c82_9a4f0c1e03a8b19d" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("160de43a_c4c2_4c82_9a4f0c1e03a8b19d"); // Initialize
}
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 39 1 0 "9786cb1f_9cde_4efb_96cfb15a70d602c3" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 40 1 0 "3c975d26_b49d_4a62_955b3f995fd950d3" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR);
// }} ""
// {{{ 41 1 0 "a4ee508e_e569_47d1_8155799ab93044dc" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-01-10 11:38$$checksum=efa78c6d$$length=087$$