// {{{ 2 "SubmethodForwardDeclaration" ""
private function CleanUp(  ) void ;
private function StartUp(  ) void ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "StartUp" "Begin"
private function StartUp(  ) void {
// }} ""
// {{ 5 "StartUp" "InitLocals"
// }} ""
// {{ 37 1 0 "c0286150_18b7_4c09_9dcea0b555b9f5ff" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_1000_channels = Translate("Tips_for_channels_1000");
// }} ""
// {{ 38 1 0 "90348b0a_9762_4d28_b0d4cb233928f827" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
tip_counter_300_channels = Translate("Tips_for_channels_300");
// }} ""
// {{{ 39 1 0 "fb05565e_10ba_4963_a88ab0a720d11901" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Read2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 40 1 0 "823b27bd_6776_49c7_8ab15cad1aa4aef1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Read2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR);
// }} ""
// {{ 41 1 0 "0f9c3c4a_de55_4a01_a60ec2184eadba39" "ML_STAR:{1C0C0CB0-7C87-11D3-AD83-0004ACB1DCB2}"
{
	variable arrRetValues[];
	arrRetValues = ML_STAR._1C0C0CB0_7C87_11D3_AD83_0004ACB1DCB2("0f9c3c4a_de55_4a01_a60ec2184eadba39"); // Initialize
}
// }} ""
// {{{ 5 "StartUp" "End"
}
// }} ""
// {{{ 5 "CleanUp" "Begin"
private function CleanUp(  ) void {
// }} ""
// {{ 5 "CleanUp" "InitLocals"
// }} ""
// {{{ 33 1 0 "9a1f9c99_ef26_48f8_9d2b61c930585769" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar1000ulHighVolumeTipWithFilter, tip_counter_1000_channels, ML_STAR);
// }} ""
// {{{ 34 1 0 "5d12662b_e8e7_4777_839b850980fc6b10" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TipCount::Write2(ML_STAR.MlStar300ulStandardVolumeTipWithFilter, tip_counter_300_channels, ML_STAR);
// }} ""
// {{{ 35 1 0 "8b8c4ee4_985e_4ca3_8db46e1263805cf5" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
COMMON96HEADSUBMETHODS::Clear96HeadAndArm(ML_STAR);
// }} ""
// {{{ 5 "CleanUp" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2019-01-10 11:36$$checksum=9f720e49$$length=087$$