// {{{ 2 "SubmethodForwardDeclaration" ""
private function ArrStr_FindIndex( variable & arrstrStrings[], variable strValue ) variable ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{ 86 1 0 "fe326295_4836_43b6_ad8c4f4e04f3f4d0" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 87 1 0 "79b665e1_a06a_4219_aa613dbcfdc607a6" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 88 1 0 "e3502411_b182_420e_87439ae36bfd9b4b" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
EASYPICKII_STEPS::easyStep_DeInit(ML_STAR);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "ArrStr_FindIndex" "Begin"
private function ArrStr_FindIndex( variable & arrstrStrings[], variable strValue ) variable {
// }} ""
private variable intIndex;
private variable intSize;
// {{ 5 "ArrStr_FindIndex" "InitLocals"
// }} ""
// {{ 78 1 0 "088ad5c5_9b7b_4fc9_bd6c162ef7df75b8" "{72EACF88-8D49-43e3-92C8-2F90E81E3260}"
intSize=arrstrStrings.GetSize();
// }} ""
// {{ 79 1 0 "8af626c9_f8c0_4463_8cb957250041502b" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(intIndex = 0; intIndex < intSize;)
{
intIndex = intIndex + 1;
// }} ""
// {{ 80 1 0 "5ca83249_fd8b_4c63_ac28cd71ad458281" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (arrstrStrings.ElementAt( intIndex -1) == strValue)
{
// }} ""
// {{{ 81 1 0 "a69b7f83_3b56_4491_9e032a26a41aaefc" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return (intIndex);
// }} ""
// {{ 82 1 0 "5ca83249_fd8b_4c63_ac28cd71ad458281" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 83 1 0 "8af626c9_f8c0_4463_8cb957250041502b" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{{ 84 1 0 "e39fb4d2_905a_498c_be652f2a17e7d471" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return (0);
// }} ""
// {{{ 5 "ArrStr_FindIndex" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=ljegher$$valid=0$$time=2016-07-07 23:43$$checksum=27711469$$length=086$$